// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/decoder.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package net.jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializedecodeInput")
public inline fun decodeInput(block: net.jumpaku.exprml.pb.exprml.v1.DecodeInputKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.DecodeInput =
  net.jumpaku.exprml.pb.exprml.v1.DecodeInputKt.Dsl._create(net.jumpaku.exprml.pb.exprml.v1.DecodeInput.newBuilder()).apply { block() }._build()
/**
 * ```
 * DecodeInput is the input message for the Decode method.
 * ```
 *
 * Protobuf type `exprml.v1.DecodeInput`
 */
public object DecodeInputKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: net.jumpaku.exprml.pb.exprml.v1.DecodeInput.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: net.jumpaku.exprml.pb.exprml.v1.DecodeInput.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): net.jumpaku.exprml.pb.exprml.v1.DecodeInput = _builder.build()

    /**
     * ```
     * string in JSON (and JSON-compatible YAML).
     * ```
     *
     * `string text = 1 [json_name = "text"];`
     */
    public var text: kotlin.String
      @JvmName("getText")
      get() = _builder.text
      @JvmName("setText")
      set(value) {
        _builder.text = value
      }
    /**
     * ```
     * string in JSON (and JSON-compatible YAML).
     * ```
     *
     * `string text = 1 [json_name = "text"];`
     */
    public fun clearText() {
      _builder.clearText()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun net.jumpaku.exprml.pb.exprml.v1.DecodeInput.copy(block: `net.jumpaku.exprml.pb.exprml.v1`.DecodeInputKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.DecodeInput =
  `net.jumpaku.exprml.pb.exprml.v1`.DecodeInputKt.Dsl._create(this.toBuilder()).apply { block() }._build()

