// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/evaluator.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package net.jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializeevaluateOutput")
public inline fun evaluateOutput(block: net.jumpaku.exprml.pb.exprml.v1.EvaluateOutputKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput =
  net.jumpaku.exprml.pb.exprml.v1.EvaluateOutputKt.Dsl._create(net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput.newBuilder()).apply { block() }._build()
/**
 * ```
 * EvaluateOutput is the output message for the EvaluateExpr method.
 * ```
 *
 * Protobuf type `exprml.v1.EvaluateOutput`
 */
public object EvaluateOutputKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput = _builder.build()

    /**
     * ```
     * Status of the evaluation.
     * ```
     *
     * `.exprml.v1.EvaluateOutput.Status status = 1 [json_name = "status"];`
     */
    public var status: net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput.Status
      @JvmName("getStatus")
      get() = _builder.status
      @JvmName("setStatus")
      set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @JvmName("getStatusValue")
      get() = _builder.statusValue
      @JvmName("setStatusValue")
      set(value) {
        _builder.statusValue = value
      }
    /**
     * ```
     * Status of the evaluation.
     * ```
     *
     * `.exprml.v1.EvaluateOutput.Status status = 1 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * Error message if status is not OK.
     * ```
     *
     * `string error_message = 2 [json_name = "errorMessage"];`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.errorMessage
      @JvmName("setErrorMessage")
      set(value) {
        _builder.errorMessage = value
      }
    /**
     * ```
     * Error message if status is not OK.
     * ```
     *
     * `string error_message = 2 [json_name = "errorMessage"];`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * Error path if status is not OK.
     * ```
     *
     * `.exprml.v1.Expr.Path error_path = 3 [json_name = "errorPath"];`
     */
    public var errorPath: net.jumpaku.exprml.pb.exprml.v1.Expr.Path
      @JvmName("getErrorPath")
      get() = _builder.errorPath
      @JvmName("setErrorPath")
      set(value) {
        _builder.errorPath = value
      }
    /**
     * ```
     * Error path if status is not OK.
     * ```
     *
     * `.exprml.v1.Expr.Path error_path = 3 [json_name = "errorPath"];`
     */
    public fun clearErrorPath() {
      _builder.clearErrorPath()
    }
    /**
     * ```
     * Error path if status is not OK.
     * ```
     *
     * `.exprml.v1.Expr.Path error_path = 3 [json_name = "errorPath"];`
     * @return Whether the errorPath field is set.
     */
    public fun hasErrorPath(): kotlin.Boolean {
      return _builder.hasErrorPath()
    }
    public val EvaluateOutputKt.Dsl.errorPathOrNull: net.jumpaku.exprml.pb.exprml.v1.Expr.Path?
      get() = _builder.errorPathOrNull

    /**
     * ```
     * Result of the evaluation.
     * ```
     *
     * `.exprml.v1.Value value = 4 [json_name = "value"];`
     */
    public var value: net.jumpaku.exprml.pb.exprml.v1.Value
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * ```
     * Result of the evaluation.
     * ```
     *
     * `.exprml.v1.Value value = 4 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * Result of the evaluation.
     * ```
     *
     * `.exprml.v1.Value value = 4 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }
    public val EvaluateOutputKt.Dsl.valueOrNull: net.jumpaku.exprml.pb.exprml.v1.Value?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput.copy(block: `net.jumpaku.exprml.pb.exprml.v1`.EvaluateOutputKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.EvaluateOutput =
  `net.jumpaku.exprml.pb.exprml.v1`.EvaluateOutputKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val net.jumpaku.exprml.pb.exprml.v1.EvaluateOutputOrBuilder.errorPathOrNull: net.jumpaku.exprml.pb.exprml.v1.Expr.Path?
  get() = if (hasErrorPath()) getErrorPath() else null

public val net.jumpaku.exprml.pb.exprml.v1.EvaluateOutputOrBuilder.valueOrNull: net.jumpaku.exprml.pb.exprml.v1.Value?
  get() = if (hasValue()) getValue() else null

