// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package net.jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializeobj")
public inline fun obj(block: net.jumpaku.exprml.pb.exprml.v1.ObjKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.Obj =
  net.jumpaku.exprml.pb.exprml.v1.ObjKt.Dsl._create(net.jumpaku.exprml.pb.exprml.v1.Obj.newBuilder()).apply { block() }._build()
/**
 * ```
 * Obj is an Obj expression.
 * ```
 *
 * Protobuf type `exprml.v1.Obj`
 */
public object ObjKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: net.jumpaku.exprml.pb.exprml.v1.Obj.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: net.jumpaku.exprml.pb.exprml.v1.Obj.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): net.jumpaku.exprml.pb.exprml.v1.Obj = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ObjProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Obj is an object.
     * ```
     *
     * `map<string, .exprml.v1.Expr> obj = 1 [json_name = "obj"];`
     */
     public val obj: com.google.protobuf.kotlin.DslMap<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr, ObjProxy>
      @kotlin.jvm.JvmSynthetic
      @JvmName("getObjMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.objMap
      )
    /**
     * ```
     * Obj is an object.
     * ```
     *
     * `map<string, .exprml.v1.Expr> obj = 1 [json_name = "obj"];`
     */
    @JvmName("putObj")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr, ObjProxy>
      .put(key: kotlin.String, value: net.jumpaku.exprml.pb.exprml.v1.Expr) {
         _builder.putObj(key, value)
       }
    /**
     * ```
     * Obj is an object.
     * ```
     *
     * `map<string, .exprml.v1.Expr> obj = 1 [json_name = "obj"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("setObj")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr, ObjProxy>
      .set(key: kotlin.String, value: net.jumpaku.exprml.pb.exprml.v1.Expr) {
         put(key, value)
       }
    /**
     * ```
     * Obj is an object.
     * ```
     *
     * `map<string, .exprml.v1.Expr> obj = 1 [json_name = "obj"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("removeObj")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr, ObjProxy>
      .remove(key: kotlin.String) {
         _builder.removeObj(key)
       }
    /**
     * ```
     * Obj is an object.
     * ```
     *
     * `map<string, .exprml.v1.Expr> obj = 1 [json_name = "obj"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("putAllObj")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr, ObjProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr>) {
         _builder.putAllObj(map)
       }
    /**
     * ```
     * Obj is an object.
     * ```
     *
     * `map<string, .exprml.v1.Expr> obj = 1 [json_name = "obj"];`
     */
    @kotlin.jvm.JvmSynthetic
    @JvmName("clearObj")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, net.jumpaku.exprml.pb.exprml.v1.Expr, ObjProxy>
      .clear() {
         _builder.clearObj()
       }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun net.jumpaku.exprml.pb.exprml.v1.Obj.copy(block: `net.jumpaku.exprml.pb.exprml.v1`.ObjKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.Obj =
  `net.jumpaku.exprml.pb.exprml.v1`.ObjKt.Dsl._create(this.toBuilder()).apply { block() }._build()

