// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/parser.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package net.jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializeparseInput")
public inline fun parseInput(block: net.jumpaku.exprml.pb.exprml.v1.ParseInputKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.ParseInput =
  net.jumpaku.exprml.pb.exprml.v1.ParseInputKt.Dsl._create(net.jumpaku.exprml.pb.exprml.v1.ParseInput.newBuilder()).apply { block() }._build()
/**
 * ```
 * ParseInput is the input message for the Parse method.
 * ```
 *
 * Protobuf type `exprml.v1.ParseInput`
 */
public object ParseInputKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: net.jumpaku.exprml.pb.exprml.v1.ParseInput.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: net.jumpaku.exprml.pb.exprml.v1.ParseInput.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): net.jumpaku.exprml.pb.exprml.v1.ParseInput = _builder.build()

    /**
     * ```
     * JSON value to parse.
     * ```
     *
     * `.exprml.v1.Value value = 1 [json_name = "value"];`
     */
    public var value: net.jumpaku.exprml.pb.exprml.v1.Value
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * ```
     * JSON value to parse.
     * ```
     *
     * `.exprml.v1.Value value = 1 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * JSON value to parse.
     * ```
     *
     * `.exprml.v1.Value value = 1 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }
    public val ParseInputKt.Dsl.valueOrNull: net.jumpaku.exprml.pb.exprml.v1.Value?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun net.jumpaku.exprml.pb.exprml.v1.ParseInput.copy(block: `net.jumpaku.exprml.pb.exprml.v1`.ParseInputKt.Dsl.() -> kotlin.Unit): net.jumpaku.exprml.pb.exprml.v1.ParseInput =
  `net.jumpaku.exprml.pb.exprml.v1`.ParseInputKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val net.jumpaku.exprml.pb.exprml.v1.ParseInputOrBuilder.valueOrNull: net.jumpaku.exprml.pb.exprml.v1.Value?
  get() = if (hasValue()) getValue() else null

