// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/decoder.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

public interface DecodeInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.DecodeInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * YAML string to decode.
   * </pre>
   *
   * <code>string yaml = 1 [json_name = "yaml"];</code>
   * @return The yaml.
   */
  java.lang.String getYaml();
  /**
   * <pre>
   * YAML string to decode.
   * </pre>
   *
   * <code>string yaml = 1 [json_name = "yaml"];</code>
   * @return The bytes for yaml.
   */
  com.google.protobuf.ByteString
      getYamlBytes();
}
