// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

/**
 * <pre>
 * Elem is an Elem expression.
 * </pre>
 *
 * Protobuf type {@code exprml.v1.Elem}
 */
public final class Elem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exprml.v1.Elem)
    ElemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Elem.class.getName());
  }
  // Use Elem.newBuilder() to construct.
  private Elem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Elem() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Elem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Elem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jumpaku.exprml.pb.exprml.v1.Elem.class, jumpaku.exprml.pb.exprml.v1.Elem.Builder.class);
  }

  private int bitField0_;
  public static final int GET_FIELD_NUMBER = 1;
  private jumpaku.exprml.pb.exprml.v1.Expr get_;
  /**
   * <pre>
   * Get is the expression to get the element.
   * </pre>
   *
   * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
   * @return Whether the get field is set.
   */
  @java.lang.Override
  public boolean hasGet() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Get is the expression to get the element.
   * </pre>
   *
   * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
   * @return The get.
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Expr getGet() {
    return get_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : get_;
  }
  /**
   * <pre>
   * Get is the expression to get the element.
   * </pre>
   *
   * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getGetOrBuilder() {
    return get_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : get_;
  }

  public static final int FROM_FIELD_NUMBER = 2;
  private jumpaku.exprml.pb.exprml.v1.Expr from_;
  /**
   * <pre>
   * From is the index to get the element.
   * </pre>
   *
   * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
   * @return Whether the from field is set.
   */
  @java.lang.Override
  public boolean hasFrom() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * From is the index to get the element.
   * </pre>
   *
   * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
   * @return The from.
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Expr getFrom() {
    return from_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : from_;
  }
  /**
   * <pre>
   * From is the index to get the element.
   * </pre>
   *
   * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getFromOrBuilder() {
    return from_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : from_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getGet());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getFrom());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getGet());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFrom());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jumpaku.exprml.pb.exprml.v1.Elem)) {
      return super.equals(obj);
    }
    jumpaku.exprml.pb.exprml.v1.Elem other = (jumpaku.exprml.pb.exprml.v1.Elem) obj;

    if (hasGet() != other.hasGet()) return false;
    if (hasGet()) {
      if (!getGet()
          .equals(other.getGet())) return false;
    }
    if (hasFrom() != other.hasFrom()) return false;
    if (hasFrom()) {
      if (!getFrom()
          .equals(other.getFrom())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasGet()) {
      hash = (37 * hash) + GET_FIELD_NUMBER;
      hash = (53 * hash) + getGet().hashCode();
    }
    if (hasFrom()) {
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jumpaku.exprml.pb.exprml.v1.Elem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jumpaku.exprml.pb.exprml.v1.Elem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jumpaku.exprml.pb.exprml.v1.Elem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jumpaku.exprml.pb.exprml.v1.Elem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Elem is an Elem expression.
   * </pre>
   *
   * Protobuf type {@code exprml.v1.Elem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exprml.v1.Elem)
      jumpaku.exprml.pb.exprml.v1.ElemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Elem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Elem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jumpaku.exprml.pb.exprml.v1.Elem.class, jumpaku.exprml.pb.exprml.v1.Elem.Builder.class);
    }

    // Construct using jumpaku.exprml.pb.exprml.v1.Elem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getGetFieldBuilder();
        getFromFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      get_ = null;
      if (getBuilder_ != null) {
        getBuilder_.dispose();
        getBuilder_ = null;
      }
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Elem_descriptor;
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Elem getDefaultInstanceForType() {
      return jumpaku.exprml.pb.exprml.v1.Elem.getDefaultInstance();
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Elem build() {
      jumpaku.exprml.pb.exprml.v1.Elem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Elem buildPartial() {
      jumpaku.exprml.pb.exprml.v1.Elem result = new jumpaku.exprml.pb.exprml.v1.Elem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(jumpaku.exprml.pb.exprml.v1.Elem result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.get_ = getBuilder_ == null
            ? get_
            : getBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.from_ = fromBuilder_ == null
            ? from_
            : fromBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jumpaku.exprml.pb.exprml.v1.Elem) {
        return mergeFrom((jumpaku.exprml.pb.exprml.v1.Elem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jumpaku.exprml.pb.exprml.v1.Elem other) {
      if (other == jumpaku.exprml.pb.exprml.v1.Elem.getDefaultInstance()) return this;
      if (other.hasGet()) {
        mergeGet(other.getGet());
      }
      if (other.hasFrom()) {
        mergeFrom(other.getFrom());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getGetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getFromFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private jumpaku.exprml.pb.exprml.v1.Expr get_;
    private com.google.protobuf.SingleFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> getBuilder_;
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     * @return Whether the get field is set.
     */
    public boolean hasGet() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     * @return The get.
     */
    public jumpaku.exprml.pb.exprml.v1.Expr getGet() {
      if (getBuilder_ == null) {
        return get_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : get_;
      } else {
        return getBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    public Builder setGet(jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (getBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        get_ = value;
      } else {
        getBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    public Builder setGet(
        jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (getBuilder_ == null) {
        get_ = builderForValue.build();
      } else {
        getBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    public Builder mergeGet(jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (getBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          get_ != null &&
          get_ != jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getGetBuilder().mergeFrom(value);
        } else {
          get_ = value;
        }
      } else {
        getBuilder_.mergeFrom(value);
      }
      if (get_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    public Builder clearGet() {
      bitField0_ = (bitField0_ & ~0x00000001);
      get_ = null;
      if (getBuilder_ != null) {
        getBuilder_.dispose();
        getBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Expr.Builder getGetBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getGetFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getGetOrBuilder() {
      if (getBuilder_ != null) {
        return getBuilder_.getMessageOrBuilder();
      } else {
        return get_ == null ?
            jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : get_;
      }
    }
    /**
     * <pre>
     * Get is the expression to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr get = 1 [json_name = "get"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getGetFieldBuilder() {
      if (getBuilder_ == null) {
        getBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getGet(),
                getParentForChildren(),
                isClean());
        get_ = null;
      }
      return getBuilder_;
    }

    private jumpaku.exprml.pb.exprml.v1.Expr from_;
    private com.google.protobuf.SingleFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> fromBuilder_;
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     * @return Whether the from field is set.
     */
    public boolean hasFrom() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     * @return The from.
     */
    public jumpaku.exprml.pb.exprml.v1.Expr getFrom() {
      if (fromBuilder_ == null) {
        return from_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : from_;
      } else {
        return fromBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    public Builder setFrom(jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (fromBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        from_ = value;
      } else {
        fromBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    public Builder setFrom(
        jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (fromBuilder_ == null) {
        from_ = builderForValue.build();
      } else {
        fromBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    public Builder mergeFrom(jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (fromBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          from_ != null &&
          from_ != jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getFromBuilder().mergeFrom(value);
        } else {
          from_ = value;
        }
      } else {
        fromBuilder_.mergeFrom(value);
      }
      if (from_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    public Builder clearFrom() {
      bitField0_ = (bitField0_ & ~0x00000002);
      from_ = null;
      if (fromBuilder_ != null) {
        fromBuilder_.dispose();
        fromBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Expr.Builder getFromBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFromFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getFromOrBuilder() {
      if (fromBuilder_ != null) {
        return fromBuilder_.getMessageOrBuilder();
      } else {
        return from_ == null ?
            jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : from_;
      }
    }
    /**
     * <pre>
     * From is the index to get the element.
     * </pre>
     *
     * <code>.exprml.v1.Expr from = 2 [json_name = "from"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getFromFieldBuilder() {
      if (fromBuilder_ == null) {
        fromBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getFrom(),
                getParentForChildren(),
                isClean());
        from_ = null;
      }
      return fromBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:exprml.v1.Elem)
  }

  // @@protoc_insertion_point(class_scope:exprml.v1.Elem)
  private static final jumpaku.exprml.pb.exprml.v1.Elem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jumpaku.exprml.pb.exprml.v1.Elem();
  }

  public static jumpaku.exprml.pb.exprml.v1.Elem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Elem>
      PARSER = new com.google.protobuf.AbstractParser<Elem>() {
    @java.lang.Override
    public Elem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Elem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Elem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Elem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

