// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

public final class ExprProto {
  private ExprProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ExprProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Expr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Expr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Expr_Path_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Expr_Path_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Expr_Path_Pos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Expr_Path_Pos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Eval_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Eval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Eval_Definition_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Eval_Definition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Scalar_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Scalar_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Ref_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Ref_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Obj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Obj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Obj_ObjEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Obj_ObjEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Arr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Arr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Json_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Json_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Iter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Iter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Elem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Elem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Call_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Call_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Call_ArgsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Call_ArgsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Cases_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Cases_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_Cases_Case_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_Cases_Case_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_OpUnary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_OpUnary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_OpBinary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_OpBinary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exprml_v1_OpVariadic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_exprml_v1_OpVariadic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024exprml/v1/expr.proto\022\texprml.v1\032\025exprm" +
      "l/v1/value.proto\"\234\007\n\004Expr\022(\n\004path\030\001 \001(\0132" +
      "\024.exprml.v1.Expr.PathR\004path\022&\n\005value\030\002 \001" +
      "(\0132\020.exprml.v1.ValueR\005value\022(\n\004kind\030\003 \001(" +
      "\0162\024.exprml.v1.Expr.KindR\004kind\022#\n\004eval\030\n " +
      "\001(\0132\017.exprml.v1.EvalR\004eval\022)\n\006scalar\030\013 \001" +
      "(\0132\021.exprml.v1.ScalarR\006scalar\022 \n\003ref\030\014 \001" +
      "(\0132\016.exprml.v1.RefR\003ref\022 \n\003obj\030\r \001(\0132\016.e" +
      "xprml.v1.ObjR\003obj\022 \n\003arr\030\016 \001(\0132\016.exprml." +
      "v1.ArrR\003arr\022#\n\004json\030\017 \001(\0132\017.exprml.v1.Js" +
      "onR\004json\022#\n\004iter\030\020 \001(\0132\017.exprml.v1.IterR" +
      "\004iter\022#\n\004elem\030\021 \001(\0132\017.exprml.v1.ElemR\004el" +
      "em\022#\n\004call\030\022 \001(\0132\017.exprml.v1.CallR\004call\022" +
      "&\n\005cases\030\023 \001(\0132\020.exprml.v1.CasesR\005cases\022" +
      "-\n\010op_unary\030\024 \001(\0132\022.exprml.v1.OpUnaryR\007o" +
      "pUnary\0220\n\top_binary\030\025 \001(\0132\023.exprml.v1.Op" +
      "BinaryR\010opBinary\0226\n\013op_variadic\030\026 \001(\0132\025." +
      "exprml.v1.OpVariadicR\nopVariadic\032a\n\004Path" +
      "\022*\n\003pos\030\001 \003(\0132\030.exprml.v1.Expr.Path.PosR" +
      "\003pos\032-\n\003Pos\022\024\n\005index\030\001 \001(\003R\005index\022\020\n\003key" +
      "\030\002 \001(\tR\003key\"\251\001\n\004Kind\022\017\n\013UNSPECIFIED\020\000\022\010\n" +
      "\004EVAL\020\n\022\n\n\006SCALAR\020\013\022\007\n\003REF\020\014\022\007\n\003OBJ\020\r\022\007\n" +
      "\003ARR\020\016\022\010\n\004JSON\020\017\022\010\n\004ITER\020\020\022\010\n\004ELEM\020\021\022\010\n\004" +
      "CALL\020\022\022\t\n\005CASES\020\023\022\014\n\010OP_UNARY\020\024\022\r\n\tOP_BI" +
      "NARY\020\025\022\017\n\013OP_VARIADIC\020\026\"\272\001\n\004Eval\022#\n\004eval" +
      "\030\001 \001(\0132\017.exprml.v1.ExprR\004eval\0220\n\005where\030\002" +
      " \003(\0132\032.exprml.v1.Eval.DefinitionR\005where\032" +
      "[\n\nDefinition\022\024\n\005ident\030\001 \001(\tR\005ident\022\022\n\004a" +
      "rgs\030\002 \003(\tR\004args\022#\n\004body\030\003 \001(\0132\017.exprml.v" +
      "1.ExprR\004body\"2\n\006Scalar\022(\n\006scalar\030\001 \001(\0132\020" +
      ".exprml.v1.ValueR\006scalar\"\033\n\003Ref\022\024\n\005ident" +
      "\030\001 \001(\tR\005ident\"y\n\003Obj\022)\n\003obj\030\001 \003(\0132\027.expr" +
      "ml.v1.Obj.ObjEntryR\003obj\032G\n\010ObjEntry\022\020\n\003k" +
      "ey\030\001 \001(\tR\003key\022%\n\005value\030\002 \001(\0132\017.exprml.v1" +
      ".ExprR\005value:\0028\001\"(\n\003Arr\022!\n\003arr\030\001 \003(\0132\017.e" +
      "xprml.v1.ExprR\003arr\",\n\004Json\022$\n\004json\030\001 \001(\013" +
      "2\020.exprml.v1.ValueR\004json\"\247\001\n\004Iter\022\033\n\tpos" +
      "_ident\030\001 \001(\tR\010posIdent\022\035\n\nelem_ident\030\002 \001" +
      "(\tR\telemIdent\022!\n\003col\030\003 \001(\0132\017.exprml.v1.E" +
      "xprR\003col\022\037\n\002do\030\004 \001(\0132\017.exprml.v1.ExprR\002d" +
      "o\022\037\n\002if\030\005 \001(\0132\017.exprml.v1.ExprR\002if\"N\n\004El" +
      "em\022!\n\003get\030\001 \001(\0132\017.exprml.v1.ExprR\003get\022#\n" +
      "\004from\030\002 \001(\0132\017.exprml.v1.ExprR\004from\"\225\001\n\004C" +
      "all\022\024\n\005ident\030\001 \001(\tR\005ident\022-\n\004args\030\002 \003(\0132" +
      "\031.exprml.v1.Call.ArgsEntryR\004args\032H\n\tArgs" +
      "Entry\022\020\n\003key\030\001 \001(\tR\003key\022%\n\005value\030\002 \001(\0132\017" +
      ".exprml.v1.ExprR\005value:\0028\001\"\331\001\n\005Cases\022+\n\005" +
      "cases\030\001 \003(\0132\025.exprml.v1.Cases.CaseR\005case" +
      "s\032\242\001\n\004Case\022!\n\014is_otherwise\030\001 \001(\010R\013isOthe" +
      "rwise\022#\n\004when\030\002 \001(\0132\017.exprml.v1.ExprR\004wh" +
      "en\022#\n\004then\030\003 \001(\0132\017.exprml.v1.ExprR\004then\022" +
      "-\n\totherwise\030\004 \001(\0132\017.exprml.v1.ExprR\toth" +
      "erwise\"\256\001\n\007OpUnary\022%\n\002op\030\001 \001(\0162\025.exprml." +
      "v1.OpUnary.OpR\002op\022)\n\007operand\030\002 \001(\0132\017.exp" +
      "rml.v1.ExprR\007operand\"Q\n\002Op\022\017\n\013UNSPECIFIE" +
      "D\020\000\022\007\n\003LEN\020\001\022\007\n\003NOT\020\002\022\010\n\004FLAT\020\003\022\t\n\005FLOOR" +
      "\020\004\022\010\n\004CEIL\020\005\022\t\n\005ABORT\020\006\"\332\001\n\010OpBinary\022&\n\002" +
      "op\030\001 \001(\0162\026.exprml.v1.OpBinary.OpR\002op\022#\n\004" +
      "left\030\002 \001(\0132\017.exprml.v1.ExprR\004left\022%\n\005rig" +
      "ht\030\003 \001(\0132\017.exprml.v1.ExprR\005right\"Z\n\002Op\022\017" +
      "\n\013UNSPECIFIED\020\000\022\007\n\003SUB\020\001\022\007\n\003DIV\020\002\022\006\n\002EQ\020" +
      "\003\022\007\n\003NEQ\020\004\022\006\n\002LT\020\005\022\007\n\003LTE\020\006\022\006\n\002GT\020\007\022\007\n\003G" +
      "TE\020\010\"\303\001\n\nOpVariadic\022(\n\002op\030\001 \001(\0162\030.exprml" +
      ".v1.OpVariadic.OpR\002op\022+\n\010operands\030\002 \003(\0132" +
      "\017.exprml.v1.ExprR\010operands\"^\n\002Op\022\017\n\013UNSP" +
      "ECIFIED\020\000\022\007\n\003ADD\020\001\022\007\n\003MUL\020\002\022\007\n\003AND\020\003\022\006\n\002" +
      "OR\020\004\022\007\n\003CAT\020\005\022\007\n\003MIN\020\006\022\007\n\003MAX\020\007\022\t\n\005MERGE" +
      "\020\010Bm\n\033jumpaku.exprml.pb.exprml.v1B\tExprP" +
      "rotoP\001\242\002\003EXX\252\002\tExprml.V1\312\002\tExprml\\V1\342\002\025E" +
      "xprml\\V1\\GPBMetadata\352\002\nExprml::V1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          jumpaku.exprml.pb.exprml.v1.ValueProto.getDescriptor(),
        });
    internal_static_exprml_v1_Expr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exprml_v1_Expr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Expr_descriptor,
        new java.lang.String[] { "Path", "Value", "Kind", "Eval", "Scalar", "Ref", "Obj", "Arr", "Json", "Iter", "Elem", "Call", "Cases", "OpUnary", "OpBinary", "OpVariadic", });
    internal_static_exprml_v1_Expr_Path_descriptor =
      internal_static_exprml_v1_Expr_descriptor.getNestedTypes().get(0);
    internal_static_exprml_v1_Expr_Path_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Expr_Path_descriptor,
        new java.lang.String[] { "Pos", });
    internal_static_exprml_v1_Expr_Path_Pos_descriptor =
      internal_static_exprml_v1_Expr_Path_descriptor.getNestedTypes().get(0);
    internal_static_exprml_v1_Expr_Path_Pos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Expr_Path_Pos_descriptor,
        new java.lang.String[] { "Index", "Key", });
    internal_static_exprml_v1_Eval_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_exprml_v1_Eval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Eval_descriptor,
        new java.lang.String[] { "Eval", "Where", });
    internal_static_exprml_v1_Eval_Definition_descriptor =
      internal_static_exprml_v1_Eval_descriptor.getNestedTypes().get(0);
    internal_static_exprml_v1_Eval_Definition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Eval_Definition_descriptor,
        new java.lang.String[] { "Ident", "Args", "Body", });
    internal_static_exprml_v1_Scalar_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_exprml_v1_Scalar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Scalar_descriptor,
        new java.lang.String[] { "Scalar", });
    internal_static_exprml_v1_Ref_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_exprml_v1_Ref_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Ref_descriptor,
        new java.lang.String[] { "Ident", });
    internal_static_exprml_v1_Obj_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_exprml_v1_Obj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Obj_descriptor,
        new java.lang.String[] { "Obj", });
    internal_static_exprml_v1_Obj_ObjEntry_descriptor =
      internal_static_exprml_v1_Obj_descriptor.getNestedTypes().get(0);
    internal_static_exprml_v1_Obj_ObjEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Obj_ObjEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_exprml_v1_Arr_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_exprml_v1_Arr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Arr_descriptor,
        new java.lang.String[] { "Arr", });
    internal_static_exprml_v1_Json_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_exprml_v1_Json_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Json_descriptor,
        new java.lang.String[] { "Json", });
    internal_static_exprml_v1_Iter_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_exprml_v1_Iter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Iter_descriptor,
        new java.lang.String[] { "PosIdent", "ElemIdent", "Col", "Do", "If", });
    internal_static_exprml_v1_Elem_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_exprml_v1_Elem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Elem_descriptor,
        new java.lang.String[] { "Get", "From", });
    internal_static_exprml_v1_Call_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_exprml_v1_Call_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Call_descriptor,
        new java.lang.String[] { "Ident", "Args", });
    internal_static_exprml_v1_Call_ArgsEntry_descriptor =
      internal_static_exprml_v1_Call_descriptor.getNestedTypes().get(0);
    internal_static_exprml_v1_Call_ArgsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Call_ArgsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_exprml_v1_Cases_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_exprml_v1_Cases_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Cases_descriptor,
        new java.lang.String[] { "Cases", });
    internal_static_exprml_v1_Cases_Case_descriptor =
      internal_static_exprml_v1_Cases_descriptor.getNestedTypes().get(0);
    internal_static_exprml_v1_Cases_Case_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_Cases_Case_descriptor,
        new java.lang.String[] { "IsOtherwise", "When", "Then", "Otherwise", });
    internal_static_exprml_v1_OpUnary_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_exprml_v1_OpUnary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_OpUnary_descriptor,
        new java.lang.String[] { "Op", "Operand", });
    internal_static_exprml_v1_OpBinary_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_exprml_v1_OpBinary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_OpBinary_descriptor,
        new java.lang.String[] { "Op", "Left", "Right", });
    internal_static_exprml_v1_OpVariadic_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_exprml_v1_OpVariadic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_exprml_v1_OpVariadic_descriptor,
        new java.lang.String[] { "Op", "Operands", });
    descriptor.resolveAllFeaturesImmutable();
    jumpaku.exprml.pb.exprml.v1.ValueProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
