// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

public interface ObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.Obj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Obj is an object.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Expr&gt; obj = 1 [json_name = "obj"];</code>
   */
  int getObjCount();
  /**
   * <pre>
   * Obj is an object.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Expr&gt; obj = 1 [json_name = "obj"];</code>
   */
  boolean containsObj(
      java.lang.String key);
  /**
   * Use {@link #getObjMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Expr>
  getObj();
  /**
   * <pre>
   * Obj is an object.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Expr&gt; obj = 1 [json_name = "obj"];</code>
   */
  java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Expr>
  getObjMap();
  /**
   * <pre>
   * Obj is an object.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Expr&gt; obj = 1 [json_name = "obj"];</code>
   */
  /* nullable */
jumpaku.exprml.pb.exprml.v1.Expr getObjOrDefault(
      java.lang.String key,
      /* nullable */
jumpaku.exprml.pb.exprml.v1.Expr defaultValue);
  /**
   * <pre>
   * Obj is an object.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Expr&gt; obj = 1 [json_name = "obj"];</code>
   */
  jumpaku.exprml.pb.exprml.v1.Expr getObjOrThrow(
      java.lang.String key);
}
