// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

public interface OpBinaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.OpBinary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpBinary.Op op = 1 [json_name = "op"];</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpBinary.Op op = 1 [json_name = "op"];</code>
   * @return The op.
   */
  jumpaku.exprml.pb.exprml.v1.OpBinary.Op getOp();

  /**
   * <pre>
   * Left is the left operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr left = 2 [json_name = "left"];</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <pre>
   * Left is the left operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr left = 2 [json_name = "left"];</code>
   * @return The left.
   */
  jumpaku.exprml.pb.exprml.v1.Expr getLeft();
  /**
   * <pre>
   * Left is the left operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr left = 2 [json_name = "left"];</code>
   */
  jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getLeftOrBuilder();

  /**
   * <pre>
   * Right is the right operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr right = 3 [json_name = "right"];</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <pre>
   * Right is the right operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr right = 3 [json_name = "right"];</code>
   * @return The right.
   */
  jumpaku.exprml.pb.exprml.v1.Expr getRight();
  /**
   * <pre>
   * Right is the right operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr right = 3 [json_name = "right"];</code>
   */
  jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getRightOrBuilder();
}
