// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

public interface OpUnaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.OpUnary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
   * @return The op.
   */
  jumpaku.exprml.pb.exprml.v1.OpUnary.Op getOp();

  /**
   * <pre>
   * Operand is the operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
   * @return Whether the operand field is set.
   */
  boolean hasOperand();
  /**
   * <pre>
   * Operand is the operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
   * @return The operand.
   */
  jumpaku.exprml.pb.exprml.v1.Expr getOperand();
  /**
   * <pre>
   * Operand is the operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
   */
  jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getOperandOrBuilder();
}
