// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

/**
 * <pre>
 * OpUnary is an OpUnary expression.
 * </pre>
 *
 * Protobuf type {@code exprml.v1.OpUnary}
 */
public final class OpUnary extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exprml.v1.OpUnary)
    OpUnaryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      OpUnary.class.getName());
  }
  // Use OpUnary.newBuilder() to construct.
  private OpUnary(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OpUnary() {
    op_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_OpUnary_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_OpUnary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jumpaku.exprml.pb.exprml.v1.OpUnary.class, jumpaku.exprml.pb.exprml.v1.OpUnary.Builder.class);
  }

  /**
   * <pre>
   * Op is a operator.
   * </pre>
   *
   * Protobuf enum {@code exprml.v1.OpUnary.Op}
   */
  public enum Op
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Unspecified.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <pre>
     * Len operator.
     * </pre>
     *
     * <code>LEN = 1;</code>
     */
    LEN(1),
    /**
     * <pre>
     * Not operator.
     * </pre>
     *
     * <code>NOT = 2;</code>
     */
    NOT(2),
    /**
     * <pre>
     * Flat operator.
     * </pre>
     *
     * <code>FLAT = 3;</code>
     */
    FLAT(3),
    /**
     * <pre>
     * Floor operator.
     * </pre>
     *
     * <code>FLOOR = 4;</code>
     */
    FLOOR(4),
    /**
     * <pre>
     * Ceil operator.
     * </pre>
     *
     * <code>CEIL = 5;</code>
     */
    CEIL(5),
    /**
     * <pre>
     * Abort operator.
     * </pre>
     *
     * <code>ABORT = 6;</code>
     */
    ABORT(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Op.class.getName());
    }
    /**
     * <pre>
     * Unspecified.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * Len operator.
     * </pre>
     *
     * <code>LEN = 1;</code>
     */
    public static final int LEN_VALUE = 1;
    /**
     * <pre>
     * Not operator.
     * </pre>
     *
     * <code>NOT = 2;</code>
     */
    public static final int NOT_VALUE = 2;
    /**
     * <pre>
     * Flat operator.
     * </pre>
     *
     * <code>FLAT = 3;</code>
     */
    public static final int FLAT_VALUE = 3;
    /**
     * <pre>
     * Floor operator.
     * </pre>
     *
     * <code>FLOOR = 4;</code>
     */
    public static final int FLOOR_VALUE = 4;
    /**
     * <pre>
     * Ceil operator.
     * </pre>
     *
     * <code>CEIL = 5;</code>
     */
    public static final int CEIL_VALUE = 5;
    /**
     * <pre>
     * Abort operator.
     * </pre>
     *
     * <code>ABORT = 6;</code>
     */
    public static final int ABORT_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Op valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Op forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return LEN;
        case 2: return NOT;
        case 3: return FLAT;
        case 4: return FLOOR;
        case 5: return CEIL;
        case 6: return ABORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Op>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Op> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Op>() {
            public Op findValueByNumber(int number) {
              return Op.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jumpaku.exprml.pb.exprml.v1.OpUnary.getDescriptor().getEnumTypes().get(0);
    }

    private static final Op[] VALUES = values();

    public static Op valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Op(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:exprml.v1.OpUnary.Op)
  }

  private int bitField0_;
  public static final int OP_FIELD_NUMBER = 1;
  private int op_ = 0;
  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
   * @return The enum numeric value on the wire for op.
   */
  @java.lang.Override public int getOpValue() {
    return op_;
  }
  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
   * @return The op.
   */
  @java.lang.Override public jumpaku.exprml.pb.exprml.v1.OpUnary.Op getOp() {
    jumpaku.exprml.pb.exprml.v1.OpUnary.Op result = jumpaku.exprml.pb.exprml.v1.OpUnary.Op.forNumber(op_);
    return result == null ? jumpaku.exprml.pb.exprml.v1.OpUnary.Op.UNRECOGNIZED : result;
  }

  public static final int OPERAND_FIELD_NUMBER = 2;
  private jumpaku.exprml.pb.exprml.v1.Expr operand_;
  /**
   * <pre>
   * Operand is the operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
   * @return Whether the operand field is set.
   */
  @java.lang.Override
  public boolean hasOperand() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Operand is the operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
   * @return The operand.
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Expr getOperand() {
    return operand_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : operand_;
  }
  /**
   * <pre>
   * Operand is the operand.
   * </pre>
   *
   * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getOperandOrBuilder() {
    return operand_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : operand_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (op_ != jumpaku.exprml.pb.exprml.v1.OpUnary.Op.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, op_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getOperand());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (op_ != jumpaku.exprml.pb.exprml.v1.OpUnary.Op.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, op_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getOperand());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jumpaku.exprml.pb.exprml.v1.OpUnary)) {
      return super.equals(obj);
    }
    jumpaku.exprml.pb.exprml.v1.OpUnary other = (jumpaku.exprml.pb.exprml.v1.OpUnary) obj;

    if (op_ != other.op_) return false;
    if (hasOperand() != other.hasOperand()) return false;
    if (hasOperand()) {
      if (!getOperand()
          .equals(other.getOperand())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OP_FIELD_NUMBER;
    hash = (53 * hash) + op_;
    if (hasOperand()) {
      hash = (37 * hash) + OPERAND_FIELD_NUMBER;
      hash = (53 * hash) + getOperand().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jumpaku.exprml.pb.exprml.v1.OpUnary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jumpaku.exprml.pb.exprml.v1.OpUnary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * OpUnary is an OpUnary expression.
   * </pre>
   *
   * Protobuf type {@code exprml.v1.OpUnary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exprml.v1.OpUnary)
      jumpaku.exprml.pb.exprml.v1.OpUnaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_OpUnary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_OpUnary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jumpaku.exprml.pb.exprml.v1.OpUnary.class, jumpaku.exprml.pb.exprml.v1.OpUnary.Builder.class);
    }

    // Construct using jumpaku.exprml.pb.exprml.v1.OpUnary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getOperandFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      op_ = 0;
      operand_ = null;
      if (operandBuilder_ != null) {
        operandBuilder_.dispose();
        operandBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_OpUnary_descriptor;
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.OpUnary getDefaultInstanceForType() {
      return jumpaku.exprml.pb.exprml.v1.OpUnary.getDefaultInstance();
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.OpUnary build() {
      jumpaku.exprml.pb.exprml.v1.OpUnary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.OpUnary buildPartial() {
      jumpaku.exprml.pb.exprml.v1.OpUnary result = new jumpaku.exprml.pb.exprml.v1.OpUnary(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(jumpaku.exprml.pb.exprml.v1.OpUnary result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.op_ = op_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.operand_ = operandBuilder_ == null
            ? operand_
            : operandBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jumpaku.exprml.pb.exprml.v1.OpUnary) {
        return mergeFrom((jumpaku.exprml.pb.exprml.v1.OpUnary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jumpaku.exprml.pb.exprml.v1.OpUnary other) {
      if (other == jumpaku.exprml.pb.exprml.v1.OpUnary.getDefaultInstance()) return this;
      if (other.op_ != 0) {
        setOpValue(other.getOpValue());
      }
      if (other.hasOperand()) {
        mergeOperand(other.getOperand());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              op_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getOperandFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int op_ = 0;
    /**
     * <pre>
     * Op is the operator.
     * </pre>
     *
     * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
     * @return The enum numeric value on the wire for op.
     */
    @java.lang.Override public int getOpValue() {
      return op_;
    }
    /**
     * <pre>
     * Op is the operator.
     * </pre>
     *
     * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
     * @param value The enum numeric value on the wire for op to set.
     * @return This builder for chaining.
     */
    public Builder setOpValue(int value) {
      op_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Op is the operator.
     * </pre>
     *
     * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
     * @return The op.
     */
    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.OpUnary.Op getOp() {
      jumpaku.exprml.pb.exprml.v1.OpUnary.Op result = jumpaku.exprml.pb.exprml.v1.OpUnary.Op.forNumber(op_);
      return result == null ? jumpaku.exprml.pb.exprml.v1.OpUnary.Op.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Op is the operator.
     * </pre>
     *
     * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
     * @param value The op to set.
     * @return This builder for chaining.
     */
    public Builder setOp(jumpaku.exprml.pb.exprml.v1.OpUnary.Op value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      op_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Op is the operator.
     * </pre>
     *
     * <code>.exprml.v1.OpUnary.Op op = 1 [json_name = "op"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      op_ = 0;
      onChanged();
      return this;
    }

    private jumpaku.exprml.pb.exprml.v1.Expr operand_;
    private com.google.protobuf.SingleFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> operandBuilder_;
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     * @return Whether the operand field is set.
     */
    public boolean hasOperand() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     * @return The operand.
     */
    public jumpaku.exprml.pb.exprml.v1.Expr getOperand() {
      if (operandBuilder_ == null) {
        return operand_ == null ? jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : operand_;
      } else {
        return operandBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    public Builder setOperand(jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (operandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        operand_ = value;
      } else {
        operandBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    public Builder setOperand(
        jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (operandBuilder_ == null) {
        operand_ = builderForValue.build();
      } else {
        operandBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    public Builder mergeOperand(jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (operandBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          operand_ != null &&
          operand_ != jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getOperandBuilder().mergeFrom(value);
        } else {
          operand_ = value;
        }
      } else {
        operandBuilder_.mergeFrom(value);
      }
      if (operand_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    public Builder clearOperand() {
      bitField0_ = (bitField0_ & ~0x00000002);
      operand_ = null;
      if (operandBuilder_ != null) {
        operandBuilder_.dispose();
        operandBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Expr.Builder getOperandBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getOperandFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getOperandOrBuilder() {
      if (operandBuilder_ != null) {
        return operandBuilder_.getMessageOrBuilder();
      } else {
        return operand_ == null ?
            jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : operand_;
      }
    }
    /**
     * <pre>
     * Operand is the operand.
     * </pre>
     *
     * <code>.exprml.v1.Expr operand = 2 [json_name = "operand"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getOperandFieldBuilder() {
      if (operandBuilder_ == null) {
        operandBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            jumpaku.exprml.pb.exprml.v1.Expr, jumpaku.exprml.pb.exprml.v1.Expr.Builder, jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getOperand(),
                getParentForChildren(),
                isClean());
        operand_ = null;
      }
      return operandBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:exprml.v1.OpUnary)
  }

  // @@protoc_insertion_point(class_scope:exprml.v1.OpUnary)
  private static final jumpaku.exprml.pb.exprml.v1.OpUnary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jumpaku.exprml.pb.exprml.v1.OpUnary();
  }

  public static jumpaku.exprml.pb.exprml.v1.OpUnary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OpUnary>
      PARSER = new com.google.protobuf.AbstractParser<OpUnary>() {
    @java.lang.Override
    public OpUnary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OpUnary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OpUnary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.OpUnary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

