// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/value.proto
// Protobuf Java Version: 4.28.2

package jumpaku.exprml.pb.exprml.v1;

/**
 * <pre>
 * JSON value.
 * </pre>
 *
 * Protobuf type {@code exprml.v1.Value}
 */
public final class Value extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exprml.v1.Value)
    ValueOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Value.class.getName());
  }
  // Use Value.newBuilder() to construct.
  private Value(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Value() {
    type_ = 0;
    str_ = "";
    arr_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return jumpaku.exprml.pb.exprml.v1.ValueProto.internal_static_exprml_v1_Value_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 6:
        return internalGetObj();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return jumpaku.exprml.pb.exprml.v1.ValueProto.internal_static_exprml_v1_Value_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            jumpaku.exprml.pb.exprml.v1.Value.class, jumpaku.exprml.pb.exprml.v1.Value.Builder.class);
  }

  /**
   * <pre>
   * Type of a JSON value.
   * </pre>
   *
   * Protobuf enum {@code exprml.v1.Value.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Unspecified.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    UNSPECIFIED(0),
    /**
     * <pre>
     * Null type.
     * </pre>
     *
     * <code>NULL = 1;</code>
     */
    NULL(1),
    /**
     * <pre>
     * Boolean type.
     * </pre>
     *
     * <code>BOOL = 2;</code>
     */
    BOOL(2),
    /**
     * <pre>
     * Number type.
     * </pre>
     *
     * <code>NUM = 3;</code>
     */
    NUM(3),
    /**
     * <pre>
     * String type.
     * </pre>
     *
     * <code>STR = 4;</code>
     */
    STR(4),
    /**
     * <pre>
     * Array type.
     * </pre>
     *
     * <code>ARR = 5;</code>
     */
    ARR(5),
    /**
     * <pre>
     * Object type.
     * </pre>
     *
     * <code>OBJ = 6;</code>
     */
    OBJ(6),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Type.class.getName());
    }
    /**
     * <pre>
     * Unspecified.
     * </pre>
     *
     * <code>UNSPECIFIED = 0;</code>
     */
    public static final int UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * Null type.
     * </pre>
     *
     * <code>NULL = 1;</code>
     */
    public static final int NULL_VALUE = 1;
    /**
     * <pre>
     * Boolean type.
     * </pre>
     *
     * <code>BOOL = 2;</code>
     */
    public static final int BOOL_VALUE = 2;
    /**
     * <pre>
     * Number type.
     * </pre>
     *
     * <code>NUM = 3;</code>
     */
    public static final int NUM_VALUE = 3;
    /**
     * <pre>
     * String type.
     * </pre>
     *
     * <code>STR = 4;</code>
     */
    public static final int STR_VALUE = 4;
    /**
     * <pre>
     * Array type.
     * </pre>
     *
     * <code>ARR = 5;</code>
     */
    public static final int ARR_VALUE = 5;
    /**
     * <pre>
     * Object type.
     * </pre>
     *
     * <code>OBJ = 6;</code>
     */
    public static final int OBJ_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Type valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Type forNumber(int value) {
      switch (value) {
        case 0: return UNSPECIFIED;
        case 1: return NULL;
        case 2: return BOOL;
        case 3: return NUM;
        case 4: return STR;
        case 5: return ARR;
        case 6: return OBJ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Type> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return jumpaku.exprml.pb.exprml.v1.Value.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Type(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:exprml.v1.Value.Type)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <pre>
   * Type of the value.
   * </pre>
   *
   * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * Type of the value.
   * </pre>
   *
   * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  @java.lang.Override public jumpaku.exprml.pb.exprml.v1.Value.Type getType() {
    jumpaku.exprml.pb.exprml.v1.Value.Type result = jumpaku.exprml.pb.exprml.v1.Value.Type.forNumber(type_);
    return result == null ? jumpaku.exprml.pb.exprml.v1.Value.Type.UNRECOGNIZED : result;
  }

  public static final int BOOL_FIELD_NUMBER = 2;
  private boolean bool_ = false;
  /**
   * <pre>
   * bool has a boolean value if the type is TYPE_BOOL.
   * </pre>
   *
   * <code>bool bool = 2 [json_name = "bool"];</code>
   * @return The bool.
   */
  @java.lang.Override
  public boolean getBool() {
    return bool_;
  }

  public static final int NUM_FIELD_NUMBER = 3;
  private double num_ = 0D;
  /**
   * <pre>
   * num has a number value if the type is TYPE_NUM.
   * </pre>
   *
   * <code>double num = 3 [json_name = "num"];</code>
   * @return The num.
   */
  @java.lang.Override
  public double getNum() {
    return num_;
  }

  public static final int STR_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object str_ = "";
  /**
   * <pre>
   * str has a string value if the type is TYPE_STR.
   * </pre>
   *
   * <code>string str = 4 [json_name = "str"];</code>
   * @return The str.
   */
  @java.lang.Override
  public java.lang.String getStr() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * str has a string value if the type is TYPE_STR.
   * </pre>
   *
   * <code>string str = 4 [json_name = "str"];</code>
   * @return The bytes for str.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ARR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<jumpaku.exprml.pb.exprml.v1.Value> arr_;
  /**
   * <pre>
   * arr has an array value if the type is TYPE_ARR.
   * </pre>
   *
   * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
   */
  @java.lang.Override
  public java.util.List<jumpaku.exprml.pb.exprml.v1.Value> getArrList() {
    return arr_;
  }
  /**
   * <pre>
   * arr has an array value if the type is TYPE_ARR.
   * </pre>
   *
   * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> 
      getArrOrBuilderList() {
    return arr_;
  }
  /**
   * <pre>
   * arr has an array value if the type is TYPE_ARR.
   * </pre>
   *
   * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
   */
  @java.lang.Override
  public int getArrCount() {
    return arr_.size();
  }
  /**
   * <pre>
   * arr has an array value if the type is TYPE_ARR.
   * </pre>
   *
   * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Value getArr(int index) {
    return arr_.get(index);
  }
  /**
   * <pre>
   * arr has an array value if the type is TYPE_ARR.
   * </pre>
   *
   * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.ValueOrBuilder getArrOrBuilder(
      int index) {
    return arr_.get(index);
  }

  public static final int OBJ_FIELD_NUMBER = 6;
  private static final class ObjDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value>newDefaultInstance(
                jumpaku.exprml.pb.exprml.v1.ValueProto.internal_static_exprml_v1_Value_ObjEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> obj_;
  private com.google.protobuf.MapField<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value>
  internalGetObj() {
    if (obj_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ObjDefaultEntryHolder.defaultEntry);
    }
    return obj_;
  }
  public int getObjCount() {
    return internalGetObj().getMap().size();
  }
  /**
   * <pre>
   * obj has an object value if the type is TYPE_OBJ.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
   */
  @java.lang.Override
  public boolean containsObj(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetObj().getMap().containsKey(key);
  }
  /**
   * Use {@link #getObjMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> getObj() {
    return getObjMap();
  }
  /**
   * <pre>
   * obj has an object value if the type is TYPE_OBJ.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> getObjMap() {
    return internalGetObj().getMap();
  }
  /**
   * <pre>
   * obj has an object value if the type is TYPE_OBJ.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
   */
  @java.lang.Override
  public /* nullable */
jumpaku.exprml.pb.exprml.v1.Value getObjOrDefault(
      java.lang.String key,
      /* nullable */
jumpaku.exprml.pb.exprml.v1.Value defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> map =
        internalGetObj().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * obj has an object value if the type is TYPE_OBJ.
   * </pre>
   *
   * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
   */
  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Value getObjOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> map =
        internalGetObj().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != jumpaku.exprml.pb.exprml.v1.Value.Type.UNSPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (bool_ != false) {
      output.writeBool(2, bool_);
    }
    if (java.lang.Double.doubleToRawLongBits(num_) != 0) {
      output.writeDouble(3, num_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(str_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, str_);
    }
    for (int i = 0; i < arr_.size(); i++) {
      output.writeMessage(5, arr_.get(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetObj(),
        ObjDefaultEntryHolder.defaultEntry,
        6);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != jumpaku.exprml.pb.exprml.v1.Value.Type.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (bool_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, bool_);
    }
    if (java.lang.Double.doubleToRawLongBits(num_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, num_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(str_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, str_);
    }
    for (int i = 0; i < arr_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, arr_.get(i));
    }
    for (java.util.Map.Entry<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> entry
         : internalGetObj().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value>
      obj__ = ObjDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, obj__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof jumpaku.exprml.pb.exprml.v1.Value)) {
      return super.equals(obj);
    }
    jumpaku.exprml.pb.exprml.v1.Value other = (jumpaku.exprml.pb.exprml.v1.Value) obj;

    if (type_ != other.type_) return false;
    if (getBool()
        != other.getBool()) return false;
    if (java.lang.Double.doubleToLongBits(getNum())
        != java.lang.Double.doubleToLongBits(
            other.getNum())) return false;
    if (!getStr()
        .equals(other.getStr())) return false;
    if (!getArrList()
        .equals(other.getArrList())) return false;
    if (!internalGetObj().equals(
        other.internalGetObj())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + BOOL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBool());
    hash = (37 * hash) + NUM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNum()));
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    if (getArrCount() > 0) {
      hash = (37 * hash) + ARR_FIELD_NUMBER;
      hash = (53 * hash) + getArrList().hashCode();
    }
    if (!internalGetObj().getMap().isEmpty()) {
      hash = (37 * hash) + OBJ_FIELD_NUMBER;
      hash = (53 * hash) + internalGetObj().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static jumpaku.exprml.pb.exprml.v1.Value parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static jumpaku.exprml.pb.exprml.v1.Value parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static jumpaku.exprml.pb.exprml.v1.Value parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(jumpaku.exprml.pb.exprml.v1.Value prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * JSON value.
   * </pre>
   *
   * Protobuf type {@code exprml.v1.Value}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exprml.v1.Value)
      jumpaku.exprml.pb.exprml.v1.ValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jumpaku.exprml.pb.exprml.v1.ValueProto.internal_static_exprml_v1_Value_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetObj();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableObj();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jumpaku.exprml.pb.exprml.v1.ValueProto.internal_static_exprml_v1_Value_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jumpaku.exprml.pb.exprml.v1.Value.class, jumpaku.exprml.pb.exprml.v1.Value.Builder.class);
    }

    // Construct using jumpaku.exprml.pb.exprml.v1.Value.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      bool_ = false;
      num_ = 0D;
      str_ = "";
      if (arrBuilder_ == null) {
        arr_ = java.util.Collections.emptyList();
      } else {
        arr_ = null;
        arrBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      internalGetMutableObj().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return jumpaku.exprml.pb.exprml.v1.ValueProto.internal_static_exprml_v1_Value_descriptor;
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Value getDefaultInstanceForType() {
      return jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance();
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Value build() {
      jumpaku.exprml.pb.exprml.v1.Value result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Value buildPartial() {
      jumpaku.exprml.pb.exprml.v1.Value result = new jumpaku.exprml.pb.exprml.v1.Value(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(jumpaku.exprml.pb.exprml.v1.Value result) {
      if (arrBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.arr_ = arr_;
      } else {
        result.arr_ = arrBuilder_.build();
      }
    }

    private void buildPartial0(jumpaku.exprml.pb.exprml.v1.Value result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bool_ = bool_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.num_ = num_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.str_ = str_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.obj_ = internalGetObj().build(ObjDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof jumpaku.exprml.pb.exprml.v1.Value) {
        return mergeFrom((jumpaku.exprml.pb.exprml.v1.Value)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(jumpaku.exprml.pb.exprml.v1.Value other) {
      if (other == jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getBool() != false) {
        setBool(other.getBool());
      }
      if (other.getNum() != 0D) {
        setNum(other.getNum());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (arrBuilder_ == null) {
        if (!other.arr_.isEmpty()) {
          if (arr_.isEmpty()) {
            arr_ = other.arr_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureArrIsMutable();
            arr_.addAll(other.arr_);
          }
          onChanged();
        }
      } else {
        if (!other.arr_.isEmpty()) {
          if (arrBuilder_.isEmpty()) {
            arrBuilder_.dispose();
            arrBuilder_ = null;
            arr_ = other.arr_;
            bitField0_ = (bitField0_ & ~0x00000010);
            arrBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getArrFieldBuilder() : null;
          } else {
            arrBuilder_.addAllMessages(other.arr_);
          }
        }
      }
      internalGetMutableObj().mergeFrom(
          other.internalGetObj());
      bitField0_ |= 0x00000020;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              bool_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 25: {
              num_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 34: {
              str_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              jumpaku.exprml.pb.exprml.v1.Value m =
                  input.readMessage(
                      jumpaku.exprml.pb.exprml.v1.Value.parser(),
                      extensionRegistry);
              if (arrBuilder_ == null) {
                ensureArrIsMutable();
                arr_.add(m);
              } else {
                arrBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value>
              obj__ = input.readMessage(
                  ObjDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableObj().ensureBuilderMap().put(
                  obj__.getKey(), obj__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <pre>
     * Type of the value.
     * </pre>
     *
     * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Type of the value.
     * </pre>
     *
     * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the value.
     * </pre>
     *
     * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Value.Type getType() {
      jumpaku.exprml.pb.exprml.v1.Value.Type result = jumpaku.exprml.pb.exprml.v1.Value.Type.forNumber(type_);
      return result == null ? jumpaku.exprml.pb.exprml.v1.Value.Type.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Type of the value.
     * </pre>
     *
     * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(jumpaku.exprml.pb.exprml.v1.Value.Type value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Type of the value.
     * </pre>
     *
     * <code>.exprml.v1.Value.Type type = 1 [json_name = "type"];</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private boolean bool_ ;
    /**
     * <pre>
     * bool has a boolean value if the type is TYPE_BOOL.
     * </pre>
     *
     * <code>bool bool = 2 [json_name = "bool"];</code>
     * @return The bool.
     */
    @java.lang.Override
    public boolean getBool() {
      return bool_;
    }
    /**
     * <pre>
     * bool has a boolean value if the type is TYPE_BOOL.
     * </pre>
     *
     * <code>bool bool = 2 [json_name = "bool"];</code>
     * @param value The bool to set.
     * @return This builder for chaining.
     */
    public Builder setBool(boolean value) {

      bool_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * bool has a boolean value if the type is TYPE_BOOL.
     * </pre>
     *
     * <code>bool bool = 2 [json_name = "bool"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBool() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bool_ = false;
      onChanged();
      return this;
    }

    private double num_ ;
    /**
     * <pre>
     * num has a number value if the type is TYPE_NUM.
     * </pre>
     *
     * <code>double num = 3 [json_name = "num"];</code>
     * @return The num.
     */
    @java.lang.Override
    public double getNum() {
      return num_;
    }
    /**
     * <pre>
     * num has a number value if the type is TYPE_NUM.
     * </pre>
     *
     * <code>double num = 3 [json_name = "num"];</code>
     * @param value The num to set.
     * @return This builder for chaining.
     */
    public Builder setNum(double value) {

      num_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * num has a number value if the type is TYPE_NUM.
     * </pre>
     *
     * <code>double num = 3 [json_name = "num"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNum() {
      bitField0_ = (bitField0_ & ~0x00000004);
      num_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object str_ = "";
    /**
     * <pre>
     * str has a string value if the type is TYPE_STR.
     * </pre>
     *
     * <code>string str = 4 [json_name = "str"];</code>
     * @return The str.
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * str has a string value if the type is TYPE_STR.
     * </pre>
     *
     * <code>string str = 4 [json_name = "str"];</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * str has a string value if the type is TYPE_STR.
     * </pre>
     *
     * <code>string str = 4 [json_name = "str"];</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      str_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * str has a string value if the type is TYPE_STR.
     * </pre>
     *
     * <code>string str = 4 [json_name = "str"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {
      str_ = getDefaultInstance().getStr();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * str has a string value if the type is TYPE_STR.
     * </pre>
     *
     * <code>string str = 4 [json_name = "str"];</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      str_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.util.List<jumpaku.exprml.pb.exprml.v1.Value> arr_ =
      java.util.Collections.emptyList();
    private void ensureArrIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        arr_ = new java.util.ArrayList<jumpaku.exprml.pb.exprml.v1.Value>(arr_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Value, jumpaku.exprml.pb.exprml.v1.Value.Builder, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> arrBuilder_;

    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public java.util.List<jumpaku.exprml.pb.exprml.v1.Value> getArrList() {
      if (arrBuilder_ == null) {
        return java.util.Collections.unmodifiableList(arr_);
      } else {
        return arrBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public int getArrCount() {
      if (arrBuilder_ == null) {
        return arr_.size();
      } else {
        return arrBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Value getArr(int index) {
      if (arrBuilder_ == null) {
        return arr_.get(index);
      } else {
        return arrBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder setArr(
        int index, jumpaku.exprml.pb.exprml.v1.Value value) {
      if (arrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrIsMutable();
        arr_.set(index, value);
        onChanged();
      } else {
        arrBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder setArr(
        int index, jumpaku.exprml.pb.exprml.v1.Value.Builder builderForValue) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.set(index, builderForValue.build());
        onChanged();
      } else {
        arrBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder addArr(jumpaku.exprml.pb.exprml.v1.Value value) {
      if (arrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrIsMutable();
        arr_.add(value);
        onChanged();
      } else {
        arrBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder addArr(
        int index, jumpaku.exprml.pb.exprml.v1.Value value) {
      if (arrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrIsMutable();
        arr_.add(index, value);
        onChanged();
      } else {
        arrBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder addArr(
        jumpaku.exprml.pb.exprml.v1.Value.Builder builderForValue) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.add(builderForValue.build());
        onChanged();
      } else {
        arrBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder addArr(
        int index, jumpaku.exprml.pb.exprml.v1.Value.Builder builderForValue) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.add(index, builderForValue.build());
        onChanged();
      } else {
        arrBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder addAllArr(
        java.lang.Iterable<? extends jumpaku.exprml.pb.exprml.v1.Value> values) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arr_);
        onChanged();
      } else {
        arrBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder clearArr() {
      if (arrBuilder_ == null) {
        arr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        arrBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public Builder removeArr(int index) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.remove(index);
        onChanged();
      } else {
        arrBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Value.Builder getArrBuilder(
        int index) {
      return getArrFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.ValueOrBuilder getArrOrBuilder(
        int index) {
      if (arrBuilder_ == null) {
        return arr_.get(index);  } else {
        return arrBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public java.util.List<? extends jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> 
         getArrOrBuilderList() {
      if (arrBuilder_ != null) {
        return arrBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(arr_);
      }
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Value.Builder addArrBuilder() {
      return getArrFieldBuilder().addBuilder(
          jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance());
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Value.Builder addArrBuilder(
        int index) {
      return getArrFieldBuilder().addBuilder(
          index, jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance());
    }
    /**
     * <pre>
     * arr has an array value if the type is TYPE_ARR.
     * </pre>
     *
     * <code>repeated .exprml.v1.Value arr = 5 [json_name = "arr"];</code>
     */
    public java.util.List<jumpaku.exprml.pb.exprml.v1.Value.Builder> 
         getArrBuilderList() {
      return getArrFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        jumpaku.exprml.pb.exprml.v1.Value, jumpaku.exprml.pb.exprml.v1.Value.Builder, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> 
        getArrFieldBuilder() {
      if (arrBuilder_ == null) {
        arrBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            jumpaku.exprml.pb.exprml.v1.Value, jumpaku.exprml.pb.exprml.v1.Value.Builder, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder>(
                arr_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        arr_ = null;
      }
      return arrBuilder_;
    }

    private static final class ObjConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder, jumpaku.exprml.pb.exprml.v1.Value> {
      @java.lang.Override
      public jumpaku.exprml.pb.exprml.v1.Value build(jumpaku.exprml.pb.exprml.v1.ValueOrBuilder val) {
        if (val instanceof jumpaku.exprml.pb.exprml.v1.Value) { return (jumpaku.exprml.pb.exprml.v1.Value) val; }
        return ((jumpaku.exprml.pb.exprml.v1.Value.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> defaultEntry() {
        return ObjDefaultEntryHolder.defaultEntry;
      }
    };
    private static final ObjConverter objConverter = new ObjConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder, jumpaku.exprml.pb.exprml.v1.Value, jumpaku.exprml.pb.exprml.v1.Value.Builder> obj_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder, jumpaku.exprml.pb.exprml.v1.Value, jumpaku.exprml.pb.exprml.v1.Value.Builder>
        internalGetObj() {
      if (obj_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(objConverter);
      }
      return obj_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder, jumpaku.exprml.pb.exprml.v1.Value, jumpaku.exprml.pb.exprml.v1.Value.Builder>
        internalGetMutableObj() {
      if (obj_ == null) {
        obj_ = new com.google.protobuf.MapFieldBuilder<>(objConverter);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return obj_;
    }
    public int getObjCount() {
      return internalGetObj().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    @java.lang.Override
    public boolean containsObj(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetObj().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getObjMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> getObj() {
      return getObjMap();
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> getObjMap() {
      return internalGetObj().getImmutableMap();
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    @java.lang.Override
    public /* nullable */
jumpaku.exprml.pb.exprml.v1.Value getObjOrDefault(
        java.lang.String key,
        /* nullable */
jumpaku.exprml.pb.exprml.v1.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> map = internalGetMutableObj().ensureBuilderMap();
      return map.containsKey(key) ? objConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    @java.lang.Override
    public jumpaku.exprml.pb.exprml.v1.Value getObjOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> map = internalGetMutableObj().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return objConverter.build(map.get(key));
    }
    public Builder clearObj() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableObj().clear();
      return this;
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    public Builder removeObj(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableObj().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value>
        getMutableObj() {
      bitField0_ |= 0x00000020;
      return internalGetMutableObj().ensureMessageMap();
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    public Builder putObj(
        java.lang.String key,
        jumpaku.exprml.pb.exprml.v1.Value value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableObj().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    public Builder putAllObj(
        java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> values) {
      for (java.util.Map.Entry<java.lang.String, jumpaku.exprml.pb.exprml.v1.Value> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableObj().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <pre>
     * obj has an object value if the type is TYPE_OBJ.
     * </pre>
     *
     * <code>map&lt;string, .exprml.v1.Value&gt; obj = 6 [json_name = "obj"];</code>
     */
    public jumpaku.exprml.pb.exprml.v1.Value.Builder putObjBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> builderMap = internalGetMutableObj().ensureBuilderMap();
      jumpaku.exprml.pb.exprml.v1.ValueOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = jumpaku.exprml.pb.exprml.v1.Value.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof jumpaku.exprml.pb.exprml.v1.Value) {
        entry = ((jumpaku.exprml.pb.exprml.v1.Value) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (jumpaku.exprml.pb.exprml.v1.Value.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:exprml.v1.Value)
  }

  // @@protoc_insertion_point(class_scope:exprml.v1.Value)
  private static final jumpaku.exprml.pb.exprml.v1.Value DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new jumpaku.exprml.pb.exprml.v1.Value();
  }

  public static jumpaku.exprml.pb.exprml.v1.Value getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Value>
      PARSER = new com.google.protobuf.AbstractParser<Value>() {
    @java.lang.Override
    public Value parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Value> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Value> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public jumpaku.exprml.pb.exprml.v1.Value getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

