// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializearr")
public inline fun arr(block: jumpaku.exprml.pb.exprml.v1.ArrKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Arr =
  jumpaku.exprml.pb.exprml.v1.ArrKt.Dsl._create(jumpaku.exprml.pb.exprml.v1.Arr.newBuilder()).apply { block() }._build()
/**
 * ```
 * Arr is an Arr expression.
 * ```
 *
 * Protobuf type `exprml.v1.Arr`
 */
public object ArrKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: jumpaku.exprml.pb.exprml.v1.Arr.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jumpaku.exprml.pb.exprml.v1.Arr.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jumpaku.exprml.pb.exprml.v1.Arr = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ArrProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     */
     public val arr: com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.arrList
      )
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     * @param value The arr to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addArr")
    public fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>.add(value: jumpaku.exprml.pb.exprml.v1.Expr) {
      _builder.addArr(value)
    }
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     * @param value The arr to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignArr")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>.plusAssign(value: jumpaku.exprml.pb.exprml.v1.Expr) {
      add(value)
    }
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     * @param values The arr to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllArr")
    public fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>.addAll(values: kotlin.collections.Iterable<jumpaku.exprml.pb.exprml.v1.Expr>) {
      _builder.addAllArr(values)
    }
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     * @param values The arr to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllArr")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>.plusAssign(values: kotlin.collections.Iterable<jumpaku.exprml.pb.exprml.v1.Expr>) {
      addAll(values)
    }
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     * @param index The index to set the value at.
     * @param value The arr to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setArr")
    public operator fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>.set(index: kotlin.Int, value: jumpaku.exprml.pb.exprml.v1.Expr) {
      _builder.setArr(index, value)
    }
    /**
     * ```
     * Arr is an array.
     * ```
     *
     * `repeated .exprml.v1.Expr arr = 1 [json_name = "arr"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearArr")
    public fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Expr, ArrProxy>.clear() {
      _builder.clearArr()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun jumpaku.exprml.pb.exprml.v1.Arr.copy(block: `jumpaku.exprml.pb.exprml.v1`.ArrKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Arr =
  `jumpaku.exprml.pb.exprml.v1`.ArrKt.Dsl._create(this.toBuilder()).apply { block() }._build()

