// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/decoder.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializedecodeOutput")
public inline fun decodeOutput(block: jumpaku.exprml.pb.exprml.v1.DecodeOutputKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.DecodeOutput =
  jumpaku.exprml.pb.exprml.v1.DecodeOutputKt.Dsl._create(jumpaku.exprml.pb.exprml.v1.DecodeOutput.newBuilder()).apply { block() }._build()
/**
 * ```
 * DecodeOutput is the output message for the Decode method.
 * ```
 *
 * Protobuf type `exprml.v1.DecodeOutput`
 */
public object DecodeOutputKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: jumpaku.exprml.pb.exprml.v1.DecodeOutput.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jumpaku.exprml.pb.exprml.v1.DecodeOutput.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jumpaku.exprml.pb.exprml.v1.DecodeOutput = _builder.build()

    /**
     * ```
     * Whether an error occurred during decoding.
     * ```
     *
     * `bool is_error = 1 [json_name = "isError"];`
     */
    public var isError: kotlin.Boolean
      @JvmName("getIsError")
      get() = _builder.isError
      @JvmName("setIsError")
      set(value) {
        _builder.isError = value
      }
    /**
     * ```
     * Whether an error occurred during decoding.
     * ```
     *
     * `bool is_error = 1 [json_name = "isError"];`
     */
    public fun clearIsError() {
      _builder.clearIsError()
    }

    /**
     * ```
     * Error message if is_error is true.
     * ```
     *
     * `string error_message = 2 [json_name = "errorMessage"];`
     */
    public var errorMessage: kotlin.String
      @JvmName("getErrorMessage")
      get() = _builder.errorMessage
      @JvmName("setErrorMessage")
      set(value) {
        _builder.errorMessage = value
      }
    /**
     * ```
     * Error message if is_error is true.
     * ```
     *
     * `string error_message = 2 [json_name = "errorMessage"];`
     */
    public fun clearErrorMessage() {
      _builder.clearErrorMessage()
    }

    /**
     * ```
     * Decoded JSON value.
     * ```
     *
     * `.exprml.v1.Value value = 3 [json_name = "value"];`
     */
    public var value: jumpaku.exprml.pb.exprml.v1.Value
      @JvmName("getValue")
      get() = _builder.value
      @JvmName("setValue")
      set(value) {
        _builder.value = value
      }
    /**
     * ```
     * Decoded JSON value.
     * ```
     *
     * `.exprml.v1.Value value = 3 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * ```
     * Decoded JSON value.
     * ```
     *
     * `.exprml.v1.Value value = 3 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }
    public val DecodeOutputKt.Dsl.valueOrNull: jumpaku.exprml.pb.exprml.v1.Value?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun jumpaku.exprml.pb.exprml.v1.DecodeOutput.copy(block: `jumpaku.exprml.pb.exprml.v1`.DecodeOutputKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.DecodeOutput =
  `jumpaku.exprml.pb.exprml.v1`.DecodeOutputKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val jumpaku.exprml.pb.exprml.v1.DecodeOutputOrBuilder.valueOrNull: jumpaku.exprml.pb.exprml.v1.Value?
  get() = if (hasValue()) getValue() else null

