// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/evaluator.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializeevaluateInput")
public inline fun evaluateInput(block: jumpaku.exprml.pb.exprml.v1.EvaluateInputKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.EvaluateInput =
  jumpaku.exprml.pb.exprml.v1.EvaluateInputKt.Dsl._create(jumpaku.exprml.pb.exprml.v1.EvaluateInput.newBuilder()).apply { block() }._build()
/**
 * ```
 * EvaluateInput is the input message for the EvaluateExpr method.
 * ```
 *
 * Protobuf type `exprml.v1.EvaluateInput`
 */
public object EvaluateInputKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: jumpaku.exprml.pb.exprml.v1.EvaluateInput.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jumpaku.exprml.pb.exprml.v1.EvaluateInput.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jumpaku.exprml.pb.exprml.v1.EvaluateInput = _builder.build()

    /**
     * ```
     * Function definition stack.
     * ```
     *
     * `.exprml.v1.DefStack def_stack = 1 [json_name = "defStack"];`
     */
    public var defStack: jumpaku.exprml.pb.exprml.v1.DefStack
      @JvmName("getDefStack")
      get() = _builder.defStack
      @JvmName("setDefStack")
      set(value) {
        _builder.defStack = value
      }
    /**
     * ```
     * Function definition stack.
     * ```
     *
     * `.exprml.v1.DefStack def_stack = 1 [json_name = "defStack"];`
     */
    public fun clearDefStack() {
      _builder.clearDefStack()
    }
    /**
     * ```
     * Function definition stack.
     * ```
     *
     * `.exprml.v1.DefStack def_stack = 1 [json_name = "defStack"];`
     * @return Whether the defStack field is set.
     */
    public fun hasDefStack(): kotlin.Boolean {
      return _builder.hasDefStack()
    }
    public val EvaluateInputKt.Dsl.defStackOrNull: jumpaku.exprml.pb.exprml.v1.DefStack?
      get() = _builder.defStackOrNull

    /**
     * ```
     * Expression to evaluate.
     * ```
     *
     * `.exprml.v1.Expr expr = 2 [json_name = "expr"];`
     */
    public var expr: jumpaku.exprml.pb.exprml.v1.Expr
      @JvmName("getExpr")
      get() = _builder.expr
      @JvmName("setExpr")
      set(value) {
        _builder.expr = value
      }
    /**
     * ```
     * Expression to evaluate.
     * ```
     *
     * `.exprml.v1.Expr expr = 2 [json_name = "expr"];`
     */
    public fun clearExpr() {
      _builder.clearExpr()
    }
    /**
     * ```
     * Expression to evaluate.
     * ```
     *
     * `.exprml.v1.Expr expr = 2 [json_name = "expr"];`
     * @return Whether the expr field is set.
     */
    public fun hasExpr(): kotlin.Boolean {
      return _builder.hasExpr()
    }
    public val EvaluateInputKt.Dsl.exprOrNull: jumpaku.exprml.pb.exprml.v1.Expr?
      get() = _builder.exprOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun jumpaku.exprml.pb.exprml.v1.EvaluateInput.copy(block: `jumpaku.exprml.pb.exprml.v1`.EvaluateInputKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.EvaluateInput =
  `jumpaku.exprml.pb.exprml.v1`.EvaluateInputKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val jumpaku.exprml.pb.exprml.v1.EvaluateInputOrBuilder.defStackOrNull: jumpaku.exprml.pb.exprml.v1.DefStack?
  get() = if (hasDefStack()) getDefStack() else null

public val jumpaku.exprml.pb.exprml.v1.EvaluateInputOrBuilder.exprOrNull: jumpaku.exprml.pb.exprml.v1.Expr?
  get() = if (hasExpr()) getExpr() else null

