// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializeeval")
public inline fun eval(block: jumpaku.exprml.pb.exprml.v1.EvalKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Eval =
  jumpaku.exprml.pb.exprml.v1.EvalKt.Dsl._create(jumpaku.exprml.pb.exprml.v1.Eval.newBuilder()).apply { block() }._build()
/**
 * ```
 * Eval is an Eval expression.
 * ```
 *
 * Protobuf type `exprml.v1.Eval`
 */
public object EvalKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: jumpaku.exprml.pb.exprml.v1.Eval.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jumpaku.exprml.pb.exprml.v1.Eval.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jumpaku.exprml.pb.exprml.v1.Eval = _builder.build()

    /**
     * ```
     * Eval is an expression to evaluate.
     * ```
     *
     * `.exprml.v1.Expr eval = 1 [json_name = "eval"];`
     */
    public var eval: jumpaku.exprml.pb.exprml.v1.Expr
      @JvmName("getEval")
      get() = _builder.eval
      @JvmName("setEval")
      set(value) {
        _builder.eval = value
      }
    /**
     * ```
     * Eval is an expression to evaluate.
     * ```
     *
     * `.exprml.v1.Expr eval = 1 [json_name = "eval"];`
     */
    public fun clearEval() {
      _builder.clearEval()
    }
    /**
     * ```
     * Eval is an expression to evaluate.
     * ```
     *
     * `.exprml.v1.Expr eval = 1 [json_name = "eval"];`
     * @return Whether the eval field is set.
     */
    public fun hasEval(): kotlin.Boolean {
      return _builder.hasEval()
    }
    public val EvalKt.Dsl.evalOrNull: jumpaku.exprml.pb.exprml.v1.Expr?
      get() = _builder.evalOrNull

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WhereProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     */
     public val where: com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.whereList
      )
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     * @param value The where to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addWhere")
    public fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>.add(value: jumpaku.exprml.pb.exprml.v1.Eval.Definition) {
      _builder.addWhere(value)
    }
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     * @param value The where to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignWhere")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>.plusAssign(value: jumpaku.exprml.pb.exprml.v1.Eval.Definition) {
      add(value)
    }
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     * @param values The where to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllWhere")
    public fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>.addAll(values: kotlin.collections.Iterable<jumpaku.exprml.pb.exprml.v1.Eval.Definition>) {
      _builder.addAllWhere(values)
    }
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     * @param values The where to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllWhere")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>.plusAssign(values: kotlin.collections.Iterable<jumpaku.exprml.pb.exprml.v1.Eval.Definition>) {
      addAll(values)
    }
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     * @param index The index to set the value at.
     * @param value The where to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setWhere")
    public operator fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>.set(index: kotlin.Int, value: jumpaku.exprml.pb.exprml.v1.Eval.Definition) {
      _builder.setWhere(index, value)
    }
    /**
     * ```
     * Where is a list of definitions.
     * ```
     *
     * `repeated .exprml.v1.Eval.Definition where = 2 [json_name = "where"];`
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearWhere")
    public fun com.google.protobuf.kotlin.DslList<jumpaku.exprml.pb.exprml.v1.Eval.Definition, WhereProxy>.clear() {
      _builder.clearWhere()
    }

  }
  @kotlin.jvm.JvmName("-initializedefinition")
  public inline fun definition(block: jumpaku.exprml.pb.exprml.v1.EvalKt.DefinitionKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Eval.Definition =
    jumpaku.exprml.pb.exprml.v1.EvalKt.DefinitionKt.Dsl._create(jumpaku.exprml.pb.exprml.v1.Eval.Definition.newBuilder()).apply { block() }._build()
  /**
   * ```
   * Definition is a function or variable definition.
   * ```
   *
   * Protobuf type `exprml.v1.Eval.Definition`
   */
  public object DefinitionKt {
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    @com.google.protobuf.kotlin.ProtoDslMarker
    public class Dsl private constructor(
      private val _builder: jumpaku.exprml.pb.exprml.v1.Eval.Definition.Builder
    ) {
      public companion object {
        @kotlin.jvm.JvmSynthetic
        @kotlin.PublishedApi
        internal fun _create(builder: jumpaku.exprml.pb.exprml.v1.Eval.Definition.Builder): Dsl = Dsl(builder)
      }

      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _build(): jumpaku.exprml.pb.exprml.v1.Eval.Definition = _builder.build()

      /**
       * ```
       * Ident is the identifier of the definition.
       * ```
       *
       * `string ident = 1 [json_name = "ident"];`
       */
      public var ident: kotlin.String
        @JvmName("getIdent")
        get() = _builder.ident
        @JvmName("setIdent")
        set(value) {
          _builder.ident = value
        }
      /**
       * ```
       * Ident is the identifier of the definition.
       * ```
       *
       * `string ident = 1 [json_name = "ident"];`
       */
      public fun clearIdent() {
        _builder.clearIdent()
      }

      /**
       * An uninstantiable, behaviorless type to represent the field in
       * generics.
       */
      @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      public class ArgsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
      /**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       * @return A list containing the args.
       */
      public val args: com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>
        @kotlin.jvm.JvmSynthetic
        get() = com.google.protobuf.kotlin.DslList(
          _builder.argsList
        )
      /**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       * @param value The args to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addArgs")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>.add(value: kotlin.String) {
        _builder.addArgs(value)
      }
      /**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       * @param value The args to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignArgs")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>.plusAssign(value: kotlin.String) {
        add(value)
      }
      /**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       * @param values The args to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("addAllArgs")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
        _builder.addAllArgs(values)
      }
      /**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       * @param values The args to add.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("plusAssignAllArgs")
      @Suppress("NOTHING_TO_INLINE")
      public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
        addAll(values)
      }
      /**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       * @param index The index to set the value at.
       * @param value The args to set.
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("setArgs")
      public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>.set(index: kotlin.Int, value: kotlin.String) {
        _builder.setArgs(index, value)
      }/**
       * ```
       * Args is the list of arguments.
       * ```
       *
       * `repeated string args = 2 [json_name = "args"];`
       */
      @kotlin.jvm.JvmSynthetic
      @kotlin.jvm.JvmName("clearArgs")
      public fun com.google.protobuf.kotlin.DslList<kotlin.String, ArgsProxy>.clear() {
        _builder.clearArgs()
      }
      /**
       * ```
       * Body is the body of the definition.
       * ```
       *
       * `.exprml.v1.Expr body = 3 [json_name = "body"];`
       */
      public var body: jumpaku.exprml.pb.exprml.v1.Expr
        @JvmName("getBody")
        get() = _builder.body
        @JvmName("setBody")
        set(value) {
          _builder.body = value
        }
      /**
       * ```
       * Body is the body of the definition.
       * ```
       *
       * `.exprml.v1.Expr body = 3 [json_name = "body"];`
       */
      public fun clearBody() {
        _builder.clearBody()
      }
      /**
       * ```
       * Body is the body of the definition.
       * ```
       *
       * `.exprml.v1.Expr body = 3 [json_name = "body"];`
       * @return Whether the body field is set.
       */
      public fun hasBody(): kotlin.Boolean {
        return _builder.hasBody()
      }
      public val DefinitionKt.Dsl.bodyOrNull: jumpaku.exprml.pb.exprml.v1.Expr?
        get() = _builder.bodyOrNull
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun jumpaku.exprml.pb.exprml.v1.Eval.copy(block: `jumpaku.exprml.pb.exprml.v1`.EvalKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Eval =
  `jumpaku.exprml.pb.exprml.v1`.EvalKt.Dsl._create(this.toBuilder()).apply { block() }._build()

@kotlin.jvm.JvmSynthetic
public inline fun jumpaku.exprml.pb.exprml.v1.Eval.Definition.copy(block: `jumpaku.exprml.pb.exprml.v1`.EvalKt.DefinitionKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Eval.Definition =
  `jumpaku.exprml.pb.exprml.v1`.EvalKt.DefinitionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val jumpaku.exprml.pb.exprml.v1.Eval.DefinitionOrBuilder.bodyOrNull: jumpaku.exprml.pb.exprml.v1.Expr?
  get() = if (hasBody()) getBody() else null

public val jumpaku.exprml.pb.exprml.v1.EvalOrBuilder.evalOrNull: jumpaku.exprml.pb.exprml.v1.Expr?
  get() = if (hasEval()) getEval() else null

