// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package jumpaku.exprml.pb.exprml.v1;

@kotlin.jvm.JvmName("-initializescalar")
public inline fun scalar(block: jumpaku.exprml.pb.exprml.v1.ScalarKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Scalar =
  jumpaku.exprml.pb.exprml.v1.ScalarKt.Dsl._create(jumpaku.exprml.pb.exprml.v1.Scalar.newBuilder()).apply { block() }._build()
/**
 * ```
 * Scalar is a Scalar expression.
 * ```
 *
 * Protobuf type `exprml.v1.Scalar`
 */
public object ScalarKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: jumpaku.exprml.pb.exprml.v1.Scalar.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: jumpaku.exprml.pb.exprml.v1.Scalar.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): jumpaku.exprml.pb.exprml.v1.Scalar = _builder.build()

    /**
     * ```
     * Scalar is a scalar value.
     * ```
     *
     * `.exprml.v1.Value scalar = 1 [json_name = "scalar"];`
     */
    public var scalar: jumpaku.exprml.pb.exprml.v1.Value
      @JvmName("getScalar")
      get() = _builder.scalar
      @JvmName("setScalar")
      set(value) {
        _builder.scalar = value
      }
    /**
     * ```
     * Scalar is a scalar value.
     * ```
     *
     * `.exprml.v1.Value scalar = 1 [json_name = "scalar"];`
     */
    public fun clearScalar() {
      _builder.clearScalar()
    }
    /**
     * ```
     * Scalar is a scalar value.
     * ```
     *
     * `.exprml.v1.Value scalar = 1 [json_name = "scalar"];`
     * @return Whether the scalar field is set.
     */
    public fun hasScalar(): kotlin.Boolean {
      return _builder.hasScalar()
    }
    public val ScalarKt.Dsl.scalarOrNull: jumpaku.exprml.pb.exprml.v1.Value?
      get() = _builder.scalarOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun jumpaku.exprml.pb.exprml.v1.Scalar.copy(block: `jumpaku.exprml.pb.exprml.v1`.ScalarKt.Dsl.() -> kotlin.Unit): jumpaku.exprml.pb.exprml.v1.Scalar =
  `jumpaku.exprml.pb.exprml.v1`.ScalarKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val jumpaku.exprml.pb.exprml.v1.ScalarOrBuilder.scalarOrNull: jumpaku.exprml.pb.exprml.v1.Value?
  get() = if (hasScalar()) getScalar() else null

