// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface CasesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.Cases)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Cases is a list of cases.
   * </pre>
   *
   * <code>repeated .exprml.v1.Cases.Case cases = 1 [json_name = "cases"];</code>
   */
  java.util.List<net.jumpaku.exprml.pb.exprml.v1.Cases.Case> 
      getCasesList();
  /**
   * <pre>
   * Cases is a list of cases.
   * </pre>
   *
   * <code>repeated .exprml.v1.Cases.Case cases = 1 [json_name = "cases"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.Cases.Case getCases(int index);
  /**
   * <pre>
   * Cases is a list of cases.
   * </pre>
   *
   * <code>repeated .exprml.v1.Cases.Case cases = 1 [json_name = "cases"];</code>
   */
  int getCasesCount();
  /**
   * <pre>
   * Cases is a list of cases.
   * </pre>
   *
   * <code>repeated .exprml.v1.Cases.Case cases = 1 [json_name = "cases"];</code>
   */
  java.util.List<? extends net.jumpaku.exprml.pb.exprml.v1.Cases.CaseOrBuilder> 
      getCasesOrBuilderList();
  /**
   * <pre>
   * Cases is a list of cases.
   * </pre>
   *
   * <code>repeated .exprml.v1.Cases.Case cases = 1 [json_name = "cases"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.Cases.CaseOrBuilder getCasesOrBuilder(
      int index);
}
