// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/decoder.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface DecodeInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.DecodeInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * string in JSON (and JSON-compatible YAML).
   * </pre>
   *
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <pre>
   * string in JSON (and JSON-compatible YAML).
   * </pre>
   *
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
