// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/encoder.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface EncodeInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.EncodeInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Format of the output string.
   * </pre>
   *
   * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
   * @return The enum numeric value on the wire for format.
   */
  int getFormatValue();
  /**
   * <pre>
   * Format of the output string.
   * </pre>
   *
   * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
   * @return The format.
   */
  net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format getFormat();

  /**
   * <pre>
   * JSON value to encode.
   * </pre>
   *
   * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * JSON value to encode.
   * </pre>
   *
   * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
   * @return The value.
   */
  net.jumpaku.exprml.pb.exprml.v1.Value getValue();
  /**
   * <pre>
   * JSON value to encode.
   * </pre>
   *
   * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder getValueOrBuilder();
}
