// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/encoder.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

/**
 * <pre>
 * EncodeInput is the input message for the Encode method.
 * </pre>
 *
 * Protobuf type {@code exprml.v1.EncodeInput}
 */
public final class EncodeInput extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exprml.v1.EncodeInput)
    EncodeInputOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      EncodeInput.class.getName());
  }
  // Use EncodeInput.newBuilder() to construct.
  private EncodeInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private EncodeInput() {
    format_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.jumpaku.exprml.pb.exprml.v1.EncoderProto.internal_static_exprml_v1_EncodeInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.jumpaku.exprml.pb.exprml.v1.EncoderProto.internal_static_exprml_v1_EncodeInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.jumpaku.exprml.pb.exprml.v1.EncodeInput.class, net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Builder.class);
  }

  /**
   * <pre>
   * Format of the output string.
   * </pre>
   *
   * Protobuf enum {@code exprml.v1.EncodeInput.Format}
   */
  public enum Format
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * JSON format.
     * </pre>
     *
     * <code>JSON = 0;</code>
     */
    JSON(0),
    /**
     * <pre>
     * JSON-compatible YAML format.
     * </pre>
     *
     * <code>YAML = 1;</code>
     */
    YAML(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Format.class.getName());
    }
    /**
     * <pre>
     * JSON format.
     * </pre>
     *
     * <code>JSON = 0;</code>
     */
    public static final int JSON_VALUE = 0;
    /**
     * <pre>
     * JSON-compatible YAML format.
     * </pre>
     *
     * <code>YAML = 1;</code>
     */
    public static final int YAML_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Format valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Format forNumber(int value) {
      switch (value) {
        case 0: return JSON;
        case 1: return YAML;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Format>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Format> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Format>() {
            public Format findValueByNumber(int number) {
              return Format.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return net.jumpaku.exprml.pb.exprml.v1.EncodeInput.getDescriptor().getEnumTypes().get(0);
    }

    private static final Format[] VALUES = values();

    public static Format valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Format(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:exprml.v1.EncodeInput.Format)
  }

  private int bitField0_;
  public static final int FORMAT_FIELD_NUMBER = 1;
  private int format_ = 0;
  /**
   * <pre>
   * Format of the output string.
   * </pre>
   *
   * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
   * @return The enum numeric value on the wire for format.
   */
  @java.lang.Override public int getFormatValue() {
    return format_;
  }
  /**
   * <pre>
   * Format of the output string.
   * </pre>
   *
   * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
   * @return The format.
   */
  @java.lang.Override public net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format getFormat() {
    net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format result = net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format.forNumber(format_);
    return result == null ? net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format.UNRECOGNIZED : result;
  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private net.jumpaku.exprml.pb.exprml.v1.Value value_;
  /**
   * <pre>
   * JSON value to encode.
   * </pre>
   *
   * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * JSON value to encode.
   * </pre>
   *
   * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
   * @return The value.
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.Value getValue() {
    return value_ == null ? net.jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance() : value_;
  }
  /**
   * <pre>
   * JSON value to encode.
   * </pre>
   *
   * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder getValueOrBuilder() {
    return value_ == null ? net.jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance() : value_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (format_ != net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format.JSON.getNumber()) {
      output.writeEnum(1, format_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getValue());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (format_ != net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format.JSON.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, format_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getValue());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.jumpaku.exprml.pb.exprml.v1.EncodeInput)) {
      return super.equals(obj);
    }
    net.jumpaku.exprml.pb.exprml.v1.EncodeInput other = (net.jumpaku.exprml.pb.exprml.v1.EncodeInput) obj;

    if (format_ != other.format_) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FORMAT_FIELD_NUMBER;
    hash = (53 * hash) + format_;
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.jumpaku.exprml.pb.exprml.v1.EncodeInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * EncodeInput is the input message for the Encode method.
   * </pre>
   *
   * Protobuf type {@code exprml.v1.EncodeInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exprml.v1.EncodeInput)
      net.jumpaku.exprml.pb.exprml.v1.EncodeInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jumpaku.exprml.pb.exprml.v1.EncoderProto.internal_static_exprml_v1_EncodeInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jumpaku.exprml.pb.exprml.v1.EncoderProto.internal_static_exprml_v1_EncodeInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.jumpaku.exprml.pb.exprml.v1.EncodeInput.class, net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Builder.class);
    }

    // Construct using net.jumpaku.exprml.pb.exprml.v1.EncodeInput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getValueFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      format_ = 0;
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.jumpaku.exprml.pb.exprml.v1.EncoderProto.internal_static_exprml_v1_EncodeInput_descriptor;
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.EncodeInput getDefaultInstanceForType() {
      return net.jumpaku.exprml.pb.exprml.v1.EncodeInput.getDefaultInstance();
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.EncodeInput build() {
      net.jumpaku.exprml.pb.exprml.v1.EncodeInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.EncodeInput buildPartial() {
      net.jumpaku.exprml.pb.exprml.v1.EncodeInput result = new net.jumpaku.exprml.pb.exprml.v1.EncodeInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.jumpaku.exprml.pb.exprml.v1.EncodeInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.format_ = format_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = valueBuilder_ == null
            ? value_
            : valueBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.jumpaku.exprml.pb.exprml.v1.EncodeInput) {
        return mergeFrom((net.jumpaku.exprml.pb.exprml.v1.EncodeInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.jumpaku.exprml.pb.exprml.v1.EncodeInput other) {
      if (other == net.jumpaku.exprml.pb.exprml.v1.EncodeInput.getDefaultInstance()) return this;
      if (other.format_ != 0) {
        setFormatValue(other.getFormatValue());
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              format_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 26: {
              input.readMessage(
                  getValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int format_ = 0;
    /**
     * <pre>
     * Format of the output string.
     * </pre>
     *
     * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
     * @return The enum numeric value on the wire for format.
     */
    @java.lang.Override public int getFormatValue() {
      return format_;
    }
    /**
     * <pre>
     * Format of the output string.
     * </pre>
     *
     * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
     * @param value The enum numeric value on the wire for format to set.
     * @return This builder for chaining.
     */
    public Builder setFormatValue(int value) {
      format_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Format of the output string.
     * </pre>
     *
     * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
     * @return The format.
     */
    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format getFormat() {
      net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format result = net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format.forNumber(format_);
      return result == null ? net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Format of the output string.
     * </pre>
     *
     * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
     * @param value The format to set.
     * @return This builder for chaining.
     */
    public Builder setFormat(net.jumpaku.exprml.pb.exprml.v1.EncodeInput.Format value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      format_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Format of the output string.
     * </pre>
     *
     * <code>.exprml.v1.EncodeInput.Format format = 1 [json_name = "format"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFormat() {
      bitField0_ = (bitField0_ & ~0x00000001);
      format_ = 0;
      onChanged();
      return this;
    }

    private net.jumpaku.exprml.pb.exprml.v1.Value value_;
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Value, net.jumpaku.exprml.pb.exprml.v1.Value.Builder, net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> valueBuilder_;
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     * @return The value.
     */
    public net.jumpaku.exprml.pb.exprml.v1.Value getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? net.jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    public Builder setValue(net.jumpaku.exprml.pb.exprml.v1.Value value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    public Builder setValue(
        net.jumpaku.exprml.pb.exprml.v1.Value.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    public Builder mergeValue(net.jumpaku.exprml.pb.exprml.v1.Value value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          value_ != null &&
          value_ != net.jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance()) {
          getValueBuilder().mergeFrom(value);
        } else {
          value_ = value;
        }
      } else {
        valueBuilder_.mergeFrom(value);
      }
      if (value_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.Value.Builder getValueBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            net.jumpaku.exprml.pb.exprml.v1.Value.getDefaultInstance() : value_;
      }
    }
    /**
     * <pre>
     * JSON value to encode.
     * </pre>
     *
     * <code>.exprml.v1.Value value = 3 [json_name = "value"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Value, net.jumpaku.exprml.pb.exprml.v1.Value.Builder, net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.jumpaku.exprml.pb.exprml.v1.Value, net.jumpaku.exprml.pb.exprml.v1.Value.Builder, net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:exprml.v1.EncodeInput)
  }

  // @@protoc_insertion_point(class_scope:exprml.v1.EncodeInput)
  private static final net.jumpaku.exprml.pb.exprml.v1.EncodeInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.jumpaku.exprml.pb.exprml.v1.EncodeInput();
  }

  public static net.jumpaku.exprml.pb.exprml.v1.EncodeInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncodeInput>
      PARSER = new com.google.protobuf.AbstractParser<EncodeInput>() {
    @java.lang.Override
    public EncodeInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EncodeInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncodeInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.EncodeInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

