// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/evaluator.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface EvaluateInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.EvaluateInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Function definition stack.
   * </pre>
   *
   * <code>.exprml.v1.DefStack def_stack = 1 [json_name = "defStack"];</code>
   * @return Whether the defStack field is set.
   */
  boolean hasDefStack();
  /**
   * <pre>
   * Function definition stack.
   * </pre>
   *
   * <code>.exprml.v1.DefStack def_stack = 1 [json_name = "defStack"];</code>
   * @return The defStack.
   */
  net.jumpaku.exprml.pb.exprml.v1.DefStack getDefStack();
  /**
   * <pre>
   * Function definition stack.
   * </pre>
   *
   * <code>.exprml.v1.DefStack def_stack = 1 [json_name = "defStack"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.DefStackOrBuilder getDefStackOrBuilder();

  /**
   * <pre>
   * Expression to evaluate.
   * </pre>
   *
   * <code>.exprml.v1.Expr expr = 2 [json_name = "expr"];</code>
   * @return Whether the expr field is set.
   */
  boolean hasExpr();
  /**
   * <pre>
   * Expression to evaluate.
   * </pre>
   *
   * <code>.exprml.v1.Expr expr = 2 [json_name = "expr"];</code>
   * @return The expr.
   */
  net.jumpaku.exprml.pb.exprml.v1.Expr getExpr();
  /**
   * <pre>
   * Expression to evaluate.
   * </pre>
   *
   * <code>.exprml.v1.Expr expr = 2 [json_name = "expr"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getExprOrBuilder();
}
