// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

/**
 * <pre>
 * Iter is an Iter expression.
 * </pre>
 *
 * Protobuf type {@code exprml.v1.Iter}
 */
public final class Iter extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exprml.v1.Iter)
    IterOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Iter.class.getName());
  }
  // Use Iter.newBuilder() to construct.
  private Iter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Iter() {
    posIdent_ = "";
    elemIdent_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Iter_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Iter_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.jumpaku.exprml.pb.exprml.v1.Iter.class, net.jumpaku.exprml.pb.exprml.v1.Iter.Builder.class);
  }

  private int bitField0_;
  public static final int POS_IDENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object posIdent_ = "";
  /**
   * <pre>
   * PosIdent is the identifier of the position.
   * </pre>
   *
   * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
   * @return The posIdent.
   */
  @java.lang.Override
  public java.lang.String getPosIdent() {
    java.lang.Object ref = posIdent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      posIdent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * PosIdent is the identifier of the position.
   * </pre>
   *
   * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
   * @return The bytes for posIdent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPosIdentBytes() {
    java.lang.Object ref = posIdent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      posIdent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ELEM_IDENT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object elemIdent_ = "";
  /**
   * <pre>
   * ElemIdent is the identifier of the element.
   * </pre>
   *
   * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
   * @return The elemIdent.
   */
  @java.lang.Override
  public java.lang.String getElemIdent() {
    java.lang.Object ref = elemIdent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      elemIdent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ElemIdent is the identifier of the element.
   * </pre>
   *
   * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
   * @return The bytes for elemIdent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getElemIdentBytes() {
    java.lang.Object ref = elemIdent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      elemIdent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COL_FIELD_NUMBER = 3;
  private net.jumpaku.exprml.pb.exprml.v1.Expr col_;
  /**
   * <pre>
   * Col is the collection to iterate.
   * </pre>
   *
   * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
   * @return Whether the col field is set.
   */
  @java.lang.Override
  public boolean hasCol() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Col is the collection to iterate.
   * </pre>
   *
   * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
   * @return The col.
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.Expr getCol() {
    return col_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : col_;
  }
  /**
   * <pre>
   * Col is the collection to iterate.
   * </pre>
   *
   * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getColOrBuilder() {
    return col_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : col_;
  }

  public static final int DO_FIELD_NUMBER = 4;
  private net.jumpaku.exprml.pb.exprml.v1.Expr do_;
  /**
   * <pre>
   * Do is the body of the iteration.
   * </pre>
   *
   * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
   * @return Whether the do field is set.
   */
  @java.lang.Override
  public boolean hasDo() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Do is the body of the iteration.
   * </pre>
   *
   * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
   * @return The do.
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.Expr getDo() {
    return do_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : do_;
  }
  /**
   * <pre>
   * Do is the body of the iteration.
   * </pre>
   *
   * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getDoOrBuilder() {
    return do_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : do_;
  }

  public static final int IF_FIELD_NUMBER = 5;
  private net.jumpaku.exprml.pb.exprml.v1.Expr if_;
  /**
   * <pre>
   * If is the condition of the iteration.
   * </pre>
   *
   * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
   * @return Whether the if field is set.
   */
  @java.lang.Override
  public boolean hasIf() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * If is the condition of the iteration.
   * </pre>
   *
   * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
   * @return The if.
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.Expr getIf() {
    return if_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : if_;
  }
  /**
   * <pre>
   * If is the condition of the iteration.
   * </pre>
   *
   * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getIfOrBuilder() {
    return if_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : if_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(posIdent_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, posIdent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(elemIdent_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, elemIdent_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getCol());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getDo());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(5, getIf());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(posIdent_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, posIdent_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(elemIdent_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, elemIdent_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCol());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDo());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getIf());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.jumpaku.exprml.pb.exprml.v1.Iter)) {
      return super.equals(obj);
    }
    net.jumpaku.exprml.pb.exprml.v1.Iter other = (net.jumpaku.exprml.pb.exprml.v1.Iter) obj;

    if (!getPosIdent()
        .equals(other.getPosIdent())) return false;
    if (!getElemIdent()
        .equals(other.getElemIdent())) return false;
    if (hasCol() != other.hasCol()) return false;
    if (hasCol()) {
      if (!getCol()
          .equals(other.getCol())) return false;
    }
    if (hasDo() != other.hasDo()) return false;
    if (hasDo()) {
      if (!getDo()
          .equals(other.getDo())) return false;
    }
    if (hasIf() != other.hasIf()) return false;
    if (hasIf()) {
      if (!getIf()
          .equals(other.getIf())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + POS_IDENT_FIELD_NUMBER;
    hash = (53 * hash) + getPosIdent().hashCode();
    hash = (37 * hash) + ELEM_IDENT_FIELD_NUMBER;
    hash = (53 * hash) + getElemIdent().hashCode();
    if (hasCol()) {
      hash = (37 * hash) + COL_FIELD_NUMBER;
      hash = (53 * hash) + getCol().hashCode();
    }
    if (hasDo()) {
      hash = (37 * hash) + DO_FIELD_NUMBER;
      hash = (53 * hash) + getDo().hashCode();
    }
    if (hasIf()) {
      hash = (37 * hash) + IF_FIELD_NUMBER;
      hash = (53 * hash) + getIf().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.Iter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.jumpaku.exprml.pb.exprml.v1.Iter prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Iter is an Iter expression.
   * </pre>
   *
   * Protobuf type {@code exprml.v1.Iter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exprml.v1.Iter)
      net.jumpaku.exprml.pb.exprml.v1.IterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Iter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Iter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.jumpaku.exprml.pb.exprml.v1.Iter.class, net.jumpaku.exprml.pb.exprml.v1.Iter.Builder.class);
    }

    // Construct using net.jumpaku.exprml.pb.exprml.v1.Iter.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getColFieldBuilder();
        getDoFieldBuilder();
        getIfFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      posIdent_ = "";
      elemIdent_ = "";
      col_ = null;
      if (colBuilder_ != null) {
        colBuilder_.dispose();
        colBuilder_ = null;
      }
      do_ = null;
      if (doBuilder_ != null) {
        doBuilder_.dispose();
        doBuilder_ = null;
      }
      if_ = null;
      if (ifBuilder_ != null) {
        ifBuilder_.dispose();
        ifBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.jumpaku.exprml.pb.exprml.v1.ExprProto.internal_static_exprml_v1_Iter_descriptor;
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.Iter getDefaultInstanceForType() {
      return net.jumpaku.exprml.pb.exprml.v1.Iter.getDefaultInstance();
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.Iter build() {
      net.jumpaku.exprml.pb.exprml.v1.Iter result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.Iter buildPartial() {
      net.jumpaku.exprml.pb.exprml.v1.Iter result = new net.jumpaku.exprml.pb.exprml.v1.Iter(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.jumpaku.exprml.pb.exprml.v1.Iter result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.posIdent_ = posIdent_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.elemIdent_ = elemIdent_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.col_ = colBuilder_ == null
            ? col_
            : colBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.do_ = doBuilder_ == null
            ? do_
            : doBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.if_ = ifBuilder_ == null
            ? if_
            : ifBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.jumpaku.exprml.pb.exprml.v1.Iter) {
        return mergeFrom((net.jumpaku.exprml.pb.exprml.v1.Iter)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.jumpaku.exprml.pb.exprml.v1.Iter other) {
      if (other == net.jumpaku.exprml.pb.exprml.v1.Iter.getDefaultInstance()) return this;
      if (!other.getPosIdent().isEmpty()) {
        posIdent_ = other.posIdent_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getElemIdent().isEmpty()) {
        elemIdent_ = other.elemIdent_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasCol()) {
        mergeCol(other.getCol());
      }
      if (other.hasDo()) {
        mergeDo(other.getDo());
      }
      if (other.hasIf()) {
        mergeIf(other.getIf());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              posIdent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              elemIdent_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getColFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getDoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getIfFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object posIdent_ = "";
    /**
     * <pre>
     * PosIdent is the identifier of the position.
     * </pre>
     *
     * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
     * @return The posIdent.
     */
    public java.lang.String getPosIdent() {
      java.lang.Object ref = posIdent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        posIdent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * PosIdent is the identifier of the position.
     * </pre>
     *
     * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
     * @return The bytes for posIdent.
     */
    public com.google.protobuf.ByteString
        getPosIdentBytes() {
      java.lang.Object ref = posIdent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        posIdent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * PosIdent is the identifier of the position.
     * </pre>
     *
     * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
     * @param value The posIdent to set.
     * @return This builder for chaining.
     */
    public Builder setPosIdent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      posIdent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PosIdent is the identifier of the position.
     * </pre>
     *
     * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPosIdent() {
      posIdent_ = getDefaultInstance().getPosIdent();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * PosIdent is the identifier of the position.
     * </pre>
     *
     * <code>string pos_ident = 1 [json_name = "posIdent"];</code>
     * @param value The bytes for posIdent to set.
     * @return This builder for chaining.
     */
    public Builder setPosIdentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      posIdent_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object elemIdent_ = "";
    /**
     * <pre>
     * ElemIdent is the identifier of the element.
     * </pre>
     *
     * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
     * @return The elemIdent.
     */
    public java.lang.String getElemIdent() {
      java.lang.Object ref = elemIdent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        elemIdent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ElemIdent is the identifier of the element.
     * </pre>
     *
     * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
     * @return The bytes for elemIdent.
     */
    public com.google.protobuf.ByteString
        getElemIdentBytes() {
      java.lang.Object ref = elemIdent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        elemIdent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ElemIdent is the identifier of the element.
     * </pre>
     *
     * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
     * @param value The elemIdent to set.
     * @return This builder for chaining.
     */
    public Builder setElemIdent(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      elemIdent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ElemIdent is the identifier of the element.
     * </pre>
     *
     * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
     * @return This builder for chaining.
     */
    public Builder clearElemIdent() {
      elemIdent_ = getDefaultInstance().getElemIdent();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ElemIdent is the identifier of the element.
     * </pre>
     *
     * <code>string elem_ident = 2 [json_name = "elemIdent"];</code>
     * @param value The bytes for elemIdent to set.
     * @return This builder for chaining.
     */
    public Builder setElemIdentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      elemIdent_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private net.jumpaku.exprml.pb.exprml.v1.Expr col_;
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> colBuilder_;
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     * @return Whether the col field is set.
     */
    public boolean hasCol() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     * @return The col.
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr getCol() {
      if (colBuilder_ == null) {
        return col_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : col_;
      } else {
        return colBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    public Builder setCol(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (colBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        col_ = value;
      } else {
        colBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    public Builder setCol(
        net.jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (colBuilder_ == null) {
        col_ = builderForValue.build();
      } else {
        colBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    public Builder mergeCol(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (colBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          col_ != null &&
          col_ != net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getColBuilder().mergeFrom(value);
        } else {
          col_ = value;
        }
      } else {
        colBuilder_.mergeFrom(value);
      }
      if (col_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    public Builder clearCol() {
      bitField0_ = (bitField0_ & ~0x00000004);
      col_ = null;
      if (colBuilder_ != null) {
        colBuilder_.dispose();
        colBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr.Builder getColBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getColFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getColOrBuilder() {
      if (colBuilder_ != null) {
        return colBuilder_.getMessageOrBuilder();
      } else {
        return col_ == null ?
            net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : col_;
      }
    }
    /**
     * <pre>
     * Col is the collection to iterate.
     * </pre>
     *
     * <code>.exprml.v1.Expr col = 3 [json_name = "col"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getColFieldBuilder() {
      if (colBuilder_ == null) {
        colBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getCol(),
                getParentForChildren(),
                isClean());
        col_ = null;
      }
      return colBuilder_;
    }

    private net.jumpaku.exprml.pb.exprml.v1.Expr do_;
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> doBuilder_;
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     * @return Whether the do field is set.
     */
    public boolean hasDo() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     * @return The do.
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr getDo() {
      if (doBuilder_ == null) {
        return do_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : do_;
      } else {
        return doBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    public Builder setDo(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (doBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        do_ = value;
      } else {
        doBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    public Builder setDo(
        net.jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (doBuilder_ == null) {
        do_ = builderForValue.build();
      } else {
        doBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    public Builder mergeDo(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (doBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          do_ != null &&
          do_ != net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getDoBuilder().mergeFrom(value);
        } else {
          do_ = value;
        }
      } else {
        doBuilder_.mergeFrom(value);
      }
      if (do_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    public Builder clearDo() {
      bitField0_ = (bitField0_ & ~0x00000008);
      do_ = null;
      if (doBuilder_ != null) {
        doBuilder_.dispose();
        doBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr.Builder getDoBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getDoOrBuilder() {
      if (doBuilder_ != null) {
        return doBuilder_.getMessageOrBuilder();
      } else {
        return do_ == null ?
            net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : do_;
      }
    }
    /**
     * <pre>
     * Do is the body of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr do = 4 [json_name = "do"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getDoFieldBuilder() {
      if (doBuilder_ == null) {
        doBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getDo(),
                getParentForChildren(),
                isClean());
        do_ = null;
      }
      return doBuilder_;
    }

    private net.jumpaku.exprml.pb.exprml.v1.Expr if_;
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> ifBuilder_;
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     * @return Whether the if field is set.
     */
    public boolean hasIf() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     * @return The if.
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr getIf() {
      if (ifBuilder_ == null) {
        return if_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : if_;
      } else {
        return ifBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    public Builder setIf(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (ifBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        if_ = value;
      } else {
        ifBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    public Builder setIf(
        net.jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (ifBuilder_ == null) {
        if_ = builderForValue.build();
      } else {
        ifBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    public Builder mergeIf(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (ifBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          if_ != null &&
          if_ != net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getIfBuilder().mergeFrom(value);
        } else {
          if_ = value;
        }
      } else {
        ifBuilder_.mergeFrom(value);
      }
      if (if_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    public Builder clearIf() {
      bitField0_ = (bitField0_ & ~0x00000010);
      if_ = null;
      if (ifBuilder_ != null) {
        ifBuilder_.dispose();
        ifBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr.Builder getIfBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getIfFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getIfOrBuilder() {
      if (ifBuilder_ != null) {
        return ifBuilder_.getMessageOrBuilder();
      } else {
        return if_ == null ?
            net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : if_;
      }
    }
    /**
     * <pre>
     * If is the condition of the iteration.
     * </pre>
     *
     * <code>.exprml.v1.Expr if = 5 [json_name = "if"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getIfFieldBuilder() {
      if (ifBuilder_ == null) {
        ifBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getIf(),
                getParentForChildren(),
                isClean());
        if_ = null;
      }
      return ifBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:exprml.v1.Iter)
  }

  // @@protoc_insertion_point(class_scope:exprml.v1.Iter)
  private static final net.jumpaku.exprml.pb.exprml.v1.Iter DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.jumpaku.exprml.pb.exprml.v1.Iter();
  }

  public static net.jumpaku.exprml.pb.exprml.v1.Iter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Iter>
      PARSER = new com.google.protobuf.AbstractParser<Iter>() {
    @java.lang.Override
    public Iter parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Iter> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Iter> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.Iter getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

