// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface OpVariadicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.OpVariadic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpVariadic.Op op = 1 [json_name = "op"];</code>
   * @return The enum numeric value on the wire for op.
   */
  int getOpValue();
  /**
   * <pre>
   * Op is the operator.
   * </pre>
   *
   * <code>.exprml.v1.OpVariadic.Op op = 1 [json_name = "op"];</code>
   * @return The op.
   */
  net.jumpaku.exprml.pb.exprml.v1.OpVariadic.Op getOp();

  /**
   * <pre>
   * Operands is the list of operands.
   * </pre>
   *
   * <code>repeated .exprml.v1.Expr operands = 2 [json_name = "operands"];</code>
   */
  java.util.List<net.jumpaku.exprml.pb.exprml.v1.Expr> 
      getOperandsList();
  /**
   * <pre>
   * Operands is the list of operands.
   * </pre>
   *
   * <code>repeated .exprml.v1.Expr operands = 2 [json_name = "operands"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.Expr getOperands(int index);
  /**
   * <pre>
   * Operands is the list of operands.
   * </pre>
   *
   * <code>repeated .exprml.v1.Expr operands = 2 [json_name = "operands"];</code>
   */
  int getOperandsCount();
  /**
   * <pre>
   * Operands is the list of operands.
   * </pre>
   *
   * <code>repeated .exprml.v1.Expr operands = 2 [json_name = "operands"];</code>
   */
  java.util.List<? extends net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
      getOperandsOrBuilderList();
  /**
   * <pre>
   * Operands is the list of operands.
   * </pre>
   *
   * <code>repeated .exprml.v1.Expr operands = 2 [json_name = "operands"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getOperandsOrBuilder(
      int index);
}
