// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/parser.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

/**
 * <pre>
 * ParseOutput is the output message for the Parse method.
 * </pre>
 *
 * Protobuf type {@code exprml.v1.ParseOutput}
 */
public final class ParseOutput extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:exprml.v1.ParseOutput)
    ParseOutputOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      ParseOutput.class.getName());
  }
  // Use ParseOutput.newBuilder() to construct.
  private ParseOutput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ParseOutput() {
    errorMessage_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return net.jumpaku.exprml.pb.exprml.v1.ParserProto.internal_static_exprml_v1_ParseOutput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return net.jumpaku.exprml.pb.exprml.v1.ParserProto.internal_static_exprml_v1_ParseOutput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            net.jumpaku.exprml.pb.exprml.v1.ParseOutput.class, net.jumpaku.exprml.pb.exprml.v1.ParseOutput.Builder.class);
  }

  private int bitField0_;
  public static final int IS_ERROR_FIELD_NUMBER = 1;
  private boolean isError_ = false;
  /**
   * <pre>
   * Whether an error occurred during parsing.
   * </pre>
   *
   * <code>bool is_error = 1 [json_name = "isError"];</code>
   * @return The isError.
   */
  @java.lang.Override
  public boolean getIsError() {
    return isError_;
  }

  public static final int ERROR_MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object errorMessage_ = "";
  /**
   * <pre>
   * Error message if is_error is true.
   * </pre>
   *
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   * @return The errorMessage.
   */
  @java.lang.Override
  public java.lang.String getErrorMessage() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errorMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Error message if is_error is true.
   * </pre>
   *
   * <code>string error_message = 2 [json_name = "errorMessage"];</code>
   * @return The bytes for errorMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorMessageBytes() {
    java.lang.Object ref = errorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPR_FIELD_NUMBER = 3;
  private net.jumpaku.exprml.pb.exprml.v1.Expr expr_;
  /**
   * <pre>
   * Parsed Expr.
   * </pre>
   *
   * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
   * @return Whether the expr field is set.
   */
  @java.lang.Override
  public boolean hasExpr() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Parsed Expr.
   * </pre>
   *
   * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
   * @return The expr.
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.Expr getExpr() {
    return expr_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : expr_;
  }
  /**
   * <pre>
   * Parsed Expr.
   * </pre>
   *
   * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
   */
  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getExprOrBuilder() {
    return expr_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : expr_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isError_ != false) {
      output.writeBool(1, isError_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, errorMessage_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getExpr());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isError_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isError_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, errorMessage_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getExpr());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof net.jumpaku.exprml.pb.exprml.v1.ParseOutput)) {
      return super.equals(obj);
    }
    net.jumpaku.exprml.pb.exprml.v1.ParseOutput other = (net.jumpaku.exprml.pb.exprml.v1.ParseOutput) obj;

    if (getIsError()
        != other.getIsError()) return false;
    if (!getErrorMessage()
        .equals(other.getErrorMessage())) return false;
    if (hasExpr() != other.hasExpr()) return false;
    if (hasExpr()) {
      if (!getExpr()
          .equals(other.getExpr())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_ERROR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsError());
    hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getErrorMessage().hashCode();
    if (hasExpr()) {
      hash = (37 * hash) + EXPR_FIELD_NUMBER;
      hash = (53 * hash) + getExpr().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(net.jumpaku.exprml.pb.exprml.v1.ParseOutput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ParseOutput is the output message for the Parse method.
   * </pre>
   *
   * Protobuf type {@code exprml.v1.ParseOutput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exprml.v1.ParseOutput)
      net.jumpaku.exprml.pb.exprml.v1.ParseOutputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.jumpaku.exprml.pb.exprml.v1.ParserProto.internal_static_exprml_v1_ParseOutput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.jumpaku.exprml.pb.exprml.v1.ParserProto.internal_static_exprml_v1_ParseOutput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.jumpaku.exprml.pb.exprml.v1.ParseOutput.class, net.jumpaku.exprml.pb.exprml.v1.ParseOutput.Builder.class);
    }

    // Construct using net.jumpaku.exprml.pb.exprml.v1.ParseOutput.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getExprFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isError_ = false;
      errorMessage_ = "";
      expr_ = null;
      if (exprBuilder_ != null) {
        exprBuilder_.dispose();
        exprBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return net.jumpaku.exprml.pb.exprml.v1.ParserProto.internal_static_exprml_v1_ParseOutput_descriptor;
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.ParseOutput getDefaultInstanceForType() {
      return net.jumpaku.exprml.pb.exprml.v1.ParseOutput.getDefaultInstance();
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.ParseOutput build() {
      net.jumpaku.exprml.pb.exprml.v1.ParseOutput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public net.jumpaku.exprml.pb.exprml.v1.ParseOutput buildPartial() {
      net.jumpaku.exprml.pb.exprml.v1.ParseOutput result = new net.jumpaku.exprml.pb.exprml.v1.ParseOutput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(net.jumpaku.exprml.pb.exprml.v1.ParseOutput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isError_ = isError_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.errorMessage_ = errorMessage_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.expr_ = exprBuilder_ == null
            ? expr_
            : exprBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof net.jumpaku.exprml.pb.exprml.v1.ParseOutput) {
        return mergeFrom((net.jumpaku.exprml.pb.exprml.v1.ParseOutput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(net.jumpaku.exprml.pb.exprml.v1.ParseOutput other) {
      if (other == net.jumpaku.exprml.pb.exprml.v1.ParseOutput.getDefaultInstance()) return this;
      if (other.getIsError() != false) {
        setIsError(other.getIsError());
      }
      if (!other.getErrorMessage().isEmpty()) {
        errorMessage_ = other.errorMessage_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasExpr()) {
        mergeExpr(other.getExpr());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isError_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              errorMessage_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getExprFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isError_ ;
    /**
     * <pre>
     * Whether an error occurred during parsing.
     * </pre>
     *
     * <code>bool is_error = 1 [json_name = "isError"];</code>
     * @return The isError.
     */
    @java.lang.Override
    public boolean getIsError() {
      return isError_;
    }
    /**
     * <pre>
     * Whether an error occurred during parsing.
     * </pre>
     *
     * <code>bool is_error = 1 [json_name = "isError"];</code>
     * @param value The isError to set.
     * @return This builder for chaining.
     */
    public Builder setIsError(boolean value) {

      isError_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Whether an error occurred during parsing.
     * </pre>
     *
     * <code>bool is_error = 1 [json_name = "isError"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsError() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isError_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object errorMessage_ = "";
    /**
     * <pre>
     * Error message if is_error is true.
     * </pre>
     *
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @return The errorMessage.
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Error message if is_error is true.
     * </pre>
     *
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @return The bytes for errorMessage.
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Error message if is_error is true.
     * </pre>
     *
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @param value The errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      errorMessage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message if is_error is true.
     * </pre>
     *
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @return This builder for chaining.
     */
    public Builder clearErrorMessage() {
      errorMessage_ = getDefaultInstance().getErrorMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Error message if is_error is true.
     * </pre>
     *
     * <code>string error_message = 2 [json_name = "errorMessage"];</code>
     * @param value The bytes for errorMessage to set.
     * @return This builder for chaining.
     */
    public Builder setErrorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      errorMessage_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private net.jumpaku.exprml.pb.exprml.v1.Expr expr_;
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> exprBuilder_;
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     * @return Whether the expr field is set.
     */
    public boolean hasExpr() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     * @return The expr.
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr getExpr() {
      if (exprBuilder_ == null) {
        return expr_ == null ? net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : expr_;
      } else {
        return exprBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    public Builder setExpr(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (exprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expr_ = value;
      } else {
        exprBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    public Builder setExpr(
        net.jumpaku.exprml.pb.exprml.v1.Expr.Builder builderForValue) {
      if (exprBuilder_ == null) {
        expr_ = builderForValue.build();
      } else {
        exprBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    public Builder mergeExpr(net.jumpaku.exprml.pb.exprml.v1.Expr value) {
      if (exprBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          expr_ != null &&
          expr_ != net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance()) {
          getExprBuilder().mergeFrom(value);
        } else {
          expr_ = value;
        }
      } else {
        exprBuilder_.mergeFrom(value);
      }
      if (expr_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    public Builder clearExpr() {
      bitField0_ = (bitField0_ & ~0x00000004);
      expr_ = null;
      if (exprBuilder_ != null) {
        exprBuilder_.dispose();
        exprBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.Expr.Builder getExprBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getExprFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    public net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder getExprOrBuilder() {
      if (exprBuilder_ != null) {
        return exprBuilder_.getMessageOrBuilder();
      } else {
        return expr_ == null ?
            net.jumpaku.exprml.pb.exprml.v1.Expr.getDefaultInstance() : expr_;
      }
    }
    /**
     * <pre>
     * Parsed Expr.
     * </pre>
     *
     * <code>.exprml.v1.Expr expr = 3 [json_name = "expr"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder> 
        getExprFieldBuilder() {
      if (exprBuilder_ == null) {
        exprBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            net.jumpaku.exprml.pb.exprml.v1.Expr, net.jumpaku.exprml.pb.exprml.v1.Expr.Builder, net.jumpaku.exprml.pb.exprml.v1.ExprOrBuilder>(
                getExpr(),
                getParentForChildren(),
                isClean());
        expr_ = null;
      }
      return exprBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:exprml.v1.ParseOutput)
  }

  // @@protoc_insertion_point(class_scope:exprml.v1.ParseOutput)
  private static final net.jumpaku.exprml.pb.exprml.v1.ParseOutput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new net.jumpaku.exprml.pb.exprml.v1.ParseOutput();
  }

  public static net.jumpaku.exprml.pb.exprml.v1.ParseOutput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ParseOutput>
      PARSER = new com.google.protobuf.AbstractParser<ParseOutput>() {
    @java.lang.Override
    public ParseOutput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ParseOutput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ParseOutput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public net.jumpaku.exprml.pb.exprml.v1.ParseOutput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

