// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface RefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.Ref)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Ident is the identifier of the reference.
   * </pre>
   *
   * <code>string ident = 1 [json_name = "ident"];</code>
   * @return The ident.
   */
  java.lang.String getIdent();
  /**
   * <pre>
   * Ident is the identifier of the reference.
   * </pre>
   *
   * <code>string ident = 1 [json_name = "ident"];</code>
   * @return The bytes for ident.
   */
  com.google.protobuf.ByteString
      getIdentBytes();
}
