// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: exprml/v1/expr.proto
// Protobuf Java Version: 4.28.2

package net.jumpaku.exprml.pb.exprml.v1;

public interface ScalarOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exprml.v1.Scalar)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Scalar is a scalar value.
   * </pre>
   *
   * <code>.exprml.v1.Value scalar = 1 [json_name = "scalar"];</code>
   * @return Whether the scalar field is set.
   */
  boolean hasScalar();
  /**
   * <pre>
   * Scalar is a scalar value.
   * </pre>
   *
   * <code>.exprml.v1.Value scalar = 1 [json_name = "scalar"];</code>
   * @return The scalar.
   */
  net.jumpaku.exprml.pb.exprml.v1.Value getScalar();
  /**
   * <pre>
   * Scalar is a scalar value.
   * </pre>
   *
   * <code>.exprml.v1.Value scalar = 1 [json_name = "scalar"];</code>
   */
  net.jumpaku.exprml.pb.exprml.v1.ValueOrBuilder getScalarOrBuilder();
}
